/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_dim_School_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_dim_School_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-15 18:11:01
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_dim_School_edfi] @SAID='all', @Batch_Period_List='all'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="dim_School"> 

--<MappingInfoCommon>
declare @ActiveSchoolYear int = (select top 1 SchoolYear from edfi.SchoolYearType where CurrentSchoolYear=1)
--</MappingInfoCommon>

select
     [District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="District_Id">
    [edfi].[School].LocalEducationAgencyId
    --</MappingInfoStatus>
    )

    ,[School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[School_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Name">
    IsNull((
	select top (1) eo.NameOfInstitution 
	  from [edfi].EducationOrganization eo 
	 where eo.EducationOrganizationId=[edfi].[School].SchoolId
	 ),'')
    --</MappingInfoStatus>
    )

    ,[School_Grade_Cd_Low]=convert(VarChar(5),
    --<MappingInfoStatus Status="C" Column="School_Grade_Cd_Low">
	IsNull((
	select top (1) coalesce(x.XrefCode,d.CodeValue)
	  from [edfi].[SchoolGradeLevel] sgl
	  join [edfi].[Descriptor] d 
		on d.[DescriptorId]=sgl.GradeLevelDescriptorId
	  left outer
	  join CodeXref x on x.CodeCategory='Grade Level - Local to State' and x.LocalCode=d.CodeValue
	 where sgl.SchoolId=[edfi].[School].SchoolId
	 order by IsNull(x.XrefSortOrder,d.DescriptorId)
	 ),'')
	--</MappingInfoStatus>
    )

    ,[School_Grade_Cd_High]=convert(VarChar(5),
    --<MappingInfoStatus Status="C" Column="School_Grade_Cd_High">
	IsNull((
	select top (1) coalesce(x.XrefCode,d.CodeValue)
	  from [edfi].[SchoolGradeLevel] sgl
	  join [edfi].[Descriptor] d 
		on d.[DescriptorId]=sgl.GradeLevelDescriptorId
	  left outer
	  join CodeXref x on x.CodeCategory='Grade Level - Local to State' and x.LocalCode=d.CodeValue
	 where sgl.SchoolId=[edfi].[School].SchoolId
	 order by IsNull(x.XrefSortOrder,d.DescriptorId) desc
	 ),'')
    --</MappingInfoStatus>
    )

    ,[School_Principal_Name]=convert(VarChar(24),
    --<MappingInfoStatus Status="C" Column="School_Principal_Name">
	IsNull((
	select top (1) s.LastSurname + ', '+s.FirstName
	  from [edfi].[StaffEducationOrganizationAssignmentAssociation] a
	  join [edfi].[Staff] s on s.StaffUSI=a.StaffUSI
	  join edfi.descriptor d 
		on d.descriptorid=a.StaffClassificationDescriptorId and d.CodeValue='Principal'
	  where a.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Level_Cd]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Level_Cd">
	IsNull((
	select top (1) scd.CodeValue
	  from [edfi].[SchoolCategory] sc
	  join [edfi].Descriptor scd on scd.DescriptorId=sc.SchoolCategoryDescriptorId
	  where sc.SchoolId=[edfi].[School].SchoolId
	),'unk')
    --</MappingInfoStatus>
    )

    ,[School_Level_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Level_Name">
	IsNull((
	select top (1) scd.ShortDescription
	  from [edfi].[SchoolCategory] sc
	  join [edfi].Descriptor scd on scd.DescriptorId=sc.SchoolCategoryDescriptorId
	  where sc.SchoolId=[edfi].[School].SchoolId
	),'unknown')
    --</MappingInfoStatus>
    )

    ,[School_Level_Desc]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Level_Desc">
	IsNull((
	select top (1) scd.Description
	  from [edfi].[SchoolCategory] sc
	  join [edfi].Descriptor scd on scd.DescriptorId=sc.SchoolCategoryDescriptorId
	  where sc.SchoolId=[edfi].[School].SchoolId
	),'unknown')
     --</MappingInfoStatus>
    )

    ,[NCES_School_Type_Cd]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="NCES_School_Type_Cd">
    IsNull((
	select top (1) XrefCode
	  from dbo.CodeXRef x
	 where CodeCategory='School Type Codes - Local to NCES' -- 
	   and LocalCode=(select top (1) d.CodeValue
					    from [edfi].[Descriptor] d
					   where d.DescriptorId=[edfi].[School].SchoolTypeDescriptorId)
	),'')
    --</MappingInfoStatus>
    )

    ,[NCES_School_Type_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="NCES_School_Type_Name">
    IsNull((
	select top (1) XrefValue
	  from dbo.CodeXRef x
	 where CodeCategory='School Type Codes - Local to NCES' -- 
	   and LocalCode=(select top (1) d.CodeValue
					    from [edfi].[Descriptor] d
					   where d.DescriptorId=[edfi].[School].SchoolTypeDescriptorId)
	),'')
    --</MappingInfoStatus>
    )

    ,[NCES_School_Type_Desc]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="NCES_School_Type_Desc">
    IsNull((
	select top (1) XrefValue
	  from dbo.CodeXRef x
	 where CodeCategory='School Type Codes - Local to NCES' -- 
	   and LocalCode=(select top (1) d.CodeValue
					    from [edfi].[Descriptor] d
					   where d.DescriptorId=[edfi].[School].SchoolTypeDescriptorId)
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Type_Cd]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Type_Cd">
    IsNull((
	select top (1) d.CodeValue
	  from [edfi].[Descriptor] d
	 where d.DescriptorId=[edfi].[School].SchoolTypeDescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Type_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Type_Name">
    IsNull((
	select top (1) d.ShortDescription
	  from [edfi].[Descriptor] d
	 where d.DescriptorId=[edfi].[School].SchoolTypeDescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Type_Desc]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Type_Desc">
    IsNull((
	select top (1) d.Description
	  from [edfi].[Descriptor] d
	 where d.DescriptorId=[edfi].[School].SchoolTypeDescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_State_Cd]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_State_Cd">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[EducationOrganizationIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.EducationOrganizationIdentificationSystemDescriptorId
	 where ic.EducationOrganizationId=[edfi].[School].SchoolId
	   and d.CodeValue='SEA'
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Local_Cd]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Local_Cd">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[EducationOrganizationIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.EducationOrganizationIdentificationSystemDescriptorId
	 where ic.EducationOrganizationId=[edfi].[School].SchoolId
	   and d.CodeValue='LEA'
	),'')
    --</MappingInfoStatus>
    )

    ,[School_NCES_Cd]=convert(Char(5),
    --<MappingInfoStatus Status="C" Column="School_NCES_Cd">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[EducationOrganizationIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.EducationOrganizationIdentificationSystemDescriptorId
	 where ic.EducationOrganizationId=[edfi].[School].SchoolId
	   and d.CodeValue='NCES'
	),'')
    --</MappingInfoStatus>
    )

    ,[School_NCES_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="I" Column="School_NCES_Name">
    '' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Sat_School_Cd]=convert(Char(6),
    --<MappingInfoStatus Status="C" Column="School_Sat_School_Cd">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[EducationOrganizationIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.EducationOrganizationIdentificationSystemDescriptorId
	 where ic.EducationOrganizationId=[edfi].[School].SchoolId
	   and d.CodeValue='SAT'
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Unique_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="I" Column="School_Unique_Id">
    '' -- Installation/Client specific mapping
    --</MappingInfoStatus>
    )

    ,[School_Short_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Short_Name">
	IsNull((
	select top (1) eo.ShortNameOfInstitution
	  from [edfi].[EducationOrganization] eo 
	 where eo.EducationOrganizationId=[edfi].[School].SchoolId
	 ),'')
    --</MappingInfoStatus>
    )

    ,[School_Academic_Year_Began]=convert(VarChar(9),
    --<MappingInfoStatus Status="I" Column="School_Academic_Year_Began">
    0 -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Academic_Year_Ended]=convert(VarChar(9),
    --<MappingInfoStatus Status="I" Column="School_Academic_Year_Ended">
    0 -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Is_Closed_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="I" Column="School_Is_Closed_Ind">
    '-' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Principal_Email]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Principal_Email">
	IsNull((
	select top (1) email.ElectronicMailAddress
	  from [edfi].[StaffEducationOrganizationAssignmentAssociation] a
	  join [edfi].[Staff] s on s.StaffUSI=a.StaffUSI
	  join edfi.descriptor d 
		on d.descriptorid=a.StaffClassificationDescriptorId and d.CodeValue='Principal'
	  join [edfi].[StaffElectronicMail] email on email.StaffUSI=s.StaffUSI
	  where a.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Phone]=convert(VarChar(24),
    --<MappingInfoStatus Status="C" Column="School_Phone">
	IsNull((
	select top (1) t.TelephoneNumber
	  from [edfi].[EducationOrganizationInstitutionTelephone] t
	  join [edfi].[Descriptor] d on d.DescriptorId=t.InstitutionTelephoneNumberTypeDescriptorId and d.CodeValue='Main'
	 where t.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Address_1]=convert(VarChar(36),
    --<MappingInfoStatus Status="C" Column="School_Address_1">
    IsNull((
	select top (1) addr.StreetNumberName
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Address_2]=convert(VarChar(36),
    --<MappingInfoStatus Status="C" Column="School_Address_2">
    IsNull((
	select top (1) addr.ApartmentRoomSuiteNumber
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_City]=convert(VarChar(24),
    --<MappingInfoStatus Status="C" Column="School_City">
    IsNull((
	select top (1) addr.City
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_State]=convert(VarChar(2),
    --<MappingInfoStatus Status="C" Column="School_State">
    IsNull((
	select top (1) st_d.CodeValue
	  from [edfi].[EducationOrganizationAddress] addr
	  join [edfi].[Descriptor] st_d on st_d.DescriptorId=addr.StateAbbreviationDescriptorId
	 where addr.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Postal_Cd]=convert(VarChar(10),
    --<MappingInfoStatus Status="C" Column="School_Postal_Cd">
    IsNull((
	select top (1) addr.PostalCode
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
     --</MappingInfoStatus>
    )

    ,[School_Latitude]=convert(Decimal(9,6),
    --<MappingInfoStatus Status="C" Column="School_Latitude">
    IsNull((
	select top (1) addr.Latitude
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[School].SchoolId
	),0.0)
    --</MappingInfoStatus>
    )

    ,[School_Longitude]=convert(Decimal(9,6),
    --<MappingInfoStatus Status="C" Column="School_Longitude">
    IsNull((
	select top (1) addr.Longitude
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[School].SchoolId
	),0.0)
    --</MappingInfoStatus>
    )

    ,[School_Url]=convert(VarChar(100),
    --<MappingInfoStatus Status="C" Column="School_Url">
    IsNull((
	select top (1) WebSite
	  from [edfi].[EducationOrganization] eo
	 where eo.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Title1_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="School_Title1_Ind">
	case when exists (
		select *          
		from [edfi].[Descriptor] d
	   where d.DescriptorId=[edfi].[School].TitleIPartASchoolDesignationDescriptorId
	     and d.CodeValue not in ('Not A Title I School','Missing'))
	   then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[School_Title1_Cd]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Title1_Cd">
    IsNull((
	select top (1) d.CodeValue          
	  from [edfi].[Descriptor] d
	 where d.DescriptorId=[edfi].[School].TitleIPartASchoolDesignationDescriptorId
	   and d.CodeValue not in ('Not A Title I School','Missing')
	 order by d.DescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Title1_Desc]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="School_Title1_Desc">
    IsNull((
	select top (1) d.Description          
	  from [edfi].[Descriptor] d
	 where d.DescriptorId=[edfi].[School].TitleIPartASchoolDesignationDescriptorId
	   and d.CodeValue not in ('Not A Title I School','Missing')
	 order by d.DescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Magnet_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="School_Magnet_Ind">
	case when exists (
		select *          
		from [edfi].[Descriptor] d
	   where d.DescriptorId=[edfi].[School].MagnetSpecialProgramEmphasisSchoolDescriptorId )
	   then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[School_Charter_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="School_Charter_Ind">
	case when exists (
		select *          
		from [edfi].[Descriptor] d
	   where d.DescriptorId=[edfi].[School].TitleIPartASchoolDesignationDescriptorId
	     and d.CodeValue = 'Charter School' )
	   then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[School_Accountability_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="I" Column="School_Accountability_Ind">
    '-' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_NCES_Phone]=convert(VarChar(24),
    --<MappingInfoStatus Status="C" Column="School_NCES_Phone">
	IsNull((
	select top (1) t.TelephoneNumber
	  from [edfi].[EducationOrganizationInstitutionTelephone] t
	  join [edfi].[Descriptor] d on d.DescriptorId=t.InstitutionTelephoneNumberTypeDescriptorId and d.CodeValue='Main'
	 where t.EducationOrganizationId=[edfi].[School].SchoolId
	),'')
    --</MappingInfoStatus>
    )

    ,[School_NCES_Grade_Span]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_NCES_Grade_Span">
	IsNull((
	select top (1) coalesce(x.XrefCode,d.CodeValue)
	  from [edfi].[SchoolGradeLevel] sgl
	  join [edfi].[Descriptor] d 
		on d.[DescriptorId]=sgl.GradeLevelDescriptorId
	  left outer
	  join CodeXref x on x.CodeCategory='Grade Level - Local to State' and x.LocalCode=d.CodeValue
	 where sgl.SchoolId=[edfi].[School].SchoolId
	 order by IsNull(x.XrefSortOrder,d.DescriptorId)
	 ),'')
			+' - '+
	IsNull((
	select top (1) coalesce(x.XrefCode,d.CodeValue)
	  from [edfi].[SchoolGradeLevel] sgl
	  join [edfi].[Descriptor] d 
		on d.[DescriptorId]=sgl.GradeLevelDescriptorId
	  left outer
	  join CodeXref x on x.CodeCategory='Grade Level - Local to State' and x.LocalCode=d.CodeValue
	 where sgl.SchoolId=[edfi].[School].SchoolId
	 order by IsNull(x.XrefSortOrder,d.DescriptorId) desc
	 ),'')
    --</MappingInfoStatus>
    )

    ,[School_NCES_Operational_Status]=convert(VarChar(60),
    --<MappingInfoStatus Status="I" Column="School_NCES_Operational_Status">
    '--' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Special_Assistance_Status]=convert(VarChar(60),
    --<MappingInfoStatus Status="I" Column="School_Special_Assistance_Status">
    '-' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Cpr_Aed_Instruction_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="I" Column="School_Cpr_Aed_Instruction_Ind">
    '-' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Online_School_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="I" Column="School_Online_School_Ind">
    '-' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_Course_Catalog_Master_List_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="I" Column="School_Course_Catalog_Master_List_Name">
    '-' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[School_State_Reported_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="I" Column="School_State_Reported_Ind">
    '-' -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    @ActiveSchoolYear
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[School].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    getdate()
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom>
  from [edfi].[School]
 where @Batch_Period_List='all' or @ActiveSchoolYear in (select Batch_Period from @BPLtable)
   and (IsNull(@SAID,'all') in ('all','any') or [edfi].[School].SAID in (select SAID from @SAIDtable) )
  --</MappingInfoFrom>
--</MappingInfo>