/****** Object:  StoredProcedure [dbo].[sp_iMart_Load_dim_District]    Script Date: 4:40:40 PM ******/
CREATE PROCEDURE [dbo].[sp_iMart_Load_dim_District]
AS

-- ============================================================================
-- Script UTC date: 2019-04-22 13:59:06
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example: EXEC [dbo].[sp_iMart_Load_dim_District]

WITH StageData
AS (
SELECT
    -- Business Id (Concatenate Context and all Business Keys)
    -- Business Id deprecated

    -- Natural Key
    [HASH_KEY_BK]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[District_Id], '?') + CHAR(9)
    )), -- BK hash key

    -- Type 1 Field Hash
    [HASH_KEY_T1]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[District_Name], '?') + CHAR(9)
    + IsNull(A.[Superintendent_Name], '?') + CHAR(9)
    + IsNull(A.[State_Abbr], '?') + CHAR(9)
    + IsNull(A.[State_Name], '?') + CHAR(9)
    + IsNull(A.[County_Name], '?') + CHAR(9)
    + IsNull(A.[REA_Name], '?') + CHAR(9)
    + IsNull(A.[REA_Abbr], '?') + CHAR(9)
    + IsNull(A.[District_Academic_Year_Began], '?') + CHAR(9)
    + IsNull(A.[District_Academic_Year_Ended], '?') + CHAR(9)
    + IsNull(A.[District_Phone], '?') + CHAR(9)
    + IsNull(A.[District_Address_1], '?') + CHAR(9)
    + IsNull(A.[District_Address_2], '?') + CHAR(9)
    + IsNull(A.[District_City], '?') + CHAR(9)
    + IsNull(A.[District_State], '?') + CHAR(9)
    + IsNull(A.[District_Postal_Cd], '?') + CHAR(9)
    )), -- T1 hash key

    -- Type 1 C (Track Changes with Sequence) Field Hash
    -- No T1C Fields Found

    -- Type 2 Field Hash
    -- No T2 Fields Found

    -- Type 12 (Update with T2 band) Field Hash
    -- No T12 Fields Found

    -- Foreign Key Columns
    -- No Foreign Keys Found

    -- All Conform Table Columns
    [District_Id]=A.[District_Id],
    [District_Name]=A.[District_Name],
    [Superintendent_Name]=A.[Superintendent_Name],
    [State_Abbr]=A.[State_Abbr],
    [State_Name]=A.[State_Name],
    [County_Name]=A.[County_Name],
    [REA_Name]=A.[REA_Name],
    [REA_Abbr]=A.[REA_Abbr],
    [District_Academic_Year_Began]=A.[District_Academic_Year_Began],
    [District_Academic_Year_Ended]=A.[District_Academic_Year_Ended],
    [District_Phone]=A.[District_Phone],
    [District_Address_1]=A.[District_Address_1],
    [District_Address_2]=A.[District_Address_2],
    [District_City]=A.[District_City],
    [District_State]=A.[District_State],
    [District_Postal_Cd]=A.[District_Postal_Cd],
    [District_Latitude]=A.[District_Latitude],
    [District_Longitude]=A.[District_Longitude],
    [Batch_Period]=A.[Batch_Period],
    [SAID]=A.[SAID],
    [Date_Stamp]=A.[Date_Stamp],

    OES_Litho=Row_Number() OVER (ORDER BY (SELECT 1))
FROM [conform].[dim_District] A (NOLOCK)

),

DataMerge AS (
SELECT
    [MissingBusinessKey]=CASE WHEN sd.[District_Id] IS NULL THEN 1 ELSE 0 END,
    [MissingForeignKey]=0,
    [DupCount]=Row_Number() OVER(partition BY sd.[District_Id] ORDER BY sd.[Date_Stamp] DESC),
    [District_Key_Temp]=k1.[District_Key],
    [UpdateFlag]=CASE WHEN sd.[Hash_Key_T1] != k1.[Hash_Key_T1] THEN 1 ELSE 0 END,
    [NewSeqFlag]=0,
    [NewKeyFlag]=0,
    [NewRowFlag]=CASE WHEN k1.[District_Key] IS NULL THEN 1 ELSE 0 END,
    sd.*
FROM StageData sd
left outer join [tdw].[dim_District] K1
    on sd.[Hash_Key_BK] = K1.[Hash_Key_BK]

)

SELECT *,
    [District_Key]=dm.[District_Key_Temp],
    [DISCARDFLAG]=CASE WHEN [MissingForeignKey] = 1 OR [MissingBusinessKey] = 1 OR [DUPCOUNT] > 1 THEN 1 ELSE 0 END
FROM DataMerge dm
WHERE [NewRowFlag] = 1 --New Entity
   OR [NewKeyFlag] = 1 --New ADW Key (T2)
   OR [NewSeqFlag] = 1 --New Sequence (T1C)
   OR [UpdateFlag] = 1 --T1 Update
   OR [MissingBusinessKey] = 1 OR [DupCount] > 1 OR [MissingForeignKey] = 1 --Discard Record