/****** Object:  StoredProcedure [dbo].[sp_iMart_Load_dim_Student]    Script Date: 4:40:40 PM ******/
CREATE PROCEDURE [dbo].[sp_iMart_Load_dim_Student]
AS

-- ============================================================================
-- Script UTC date: 2019-04-22 13:59:06
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example: EXEC [dbo].[sp_iMart_Load_dim_Student]

WITH StageData
AS (
SELECT
    -- Business Id (Concatenate Context and all Business Keys)
    -- Business Id deprecated

    -- Natural Key
    [HASH_KEY_BK]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[Local_Student_Id], '?') + CHAR(9)
    )), -- BK hash key

    -- Type 1 Field Hash
    [HASH_KEY_T1]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[Student_Current_Enrolled_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Birth_Country_Cd], '?') + CHAR(9)
    + IsNull(A.[Student_Birth_Country_Name], '?') + CHAR(9)
    + IsNull(A.[American_Indian_Or_Alaska_Native_Ind], '?') + CHAR(9)
    + IsNull(A.[Asian_Ind], '?') + CHAR(9)
    + IsNull(A.[Black_Or_African_American_Ind], '?') + CHAR(9)
    + IsNull(A.[Native_Hawaiian_Or_Other_Pacific_Islander_Ind], '?') + CHAR(9)
    + IsNull(A.[White_Ind], '?') + CHAR(9)
    + IsNull(A.[Hispanic_Latino_Ind], '?') + CHAR(9)
    + IsNull(A.[Hispanic_Latino_Desc], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Number_Of_Races_Reported]), '?') + CHAR(9)
    + IsNull(A.[Student_Immigrant_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Migrant_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Refugee_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Current_LEP_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Grade_Level_Cd], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Grade_Level_Desc], '?') + CHAR(9)
    + IsNull(A.[Student_Current_State_Grade_Level_Cd], '?') + CHAR(9)
    + IsNull(A.[Student_Current_State_Grade_Level_Desc], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Economically_Disadvantaged_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Free_Reduced_Meal_Cd], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Free_Reduced_Meal_Desc], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Disability_Ind], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Student_Date_Entered_District]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Student_Date_Entered_USA_School]), '?') + CHAR(9)
    + IsNull(A.[Student_Resident_District], '?') + CHAR(9)
    + IsNull(A.[Student_Citizenship_Country], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Student_USA_Date_Of_Entry]), '?') + CHAR(9)
    + IsNull(A.[Student_Primary_Language], '?') + CHAR(9)
    + IsNull(A.[Student_Year_Entered_9th_Grade], '?') + CHAR(9)
    + IsNull(A.[Student_Graduation_Ind], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Student_Graduation_Date]), '?') + CHAR(9)
    + IsNull(A.[Student_Diploma_Type_Cd], '?') + CHAR(9)
    + IsNull(A.[Student_Received_Ged_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Title_1_Cd], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Homeless_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Homeless_Unaccompanied_Youth_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Current_SpEd_Eligible_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_Current_SpEd_Receiving_Ind], '?') + CHAR(9)
    + IsNull(A.[Student_SpEd_Area_of_Exceptionality], '?') + CHAR(9)
    + IsNull(A.[Student_State_Funding_Type], '?') + CHAR(9)
    + IsNull(A.[Student_Current_Gifted_Ind], '?') + CHAR(9)
    )), -- T1 hash key

    -- Type 1 C (Track Changes with Sequence) Field Hash
    [HASH_KEY_T1C]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[Student_State_Id_Nbr], '?') + CHAR(9)
    + IsNull(A.[Student_First_Name], '?') + CHAR(9)
    + IsNull(A.[Student_Middle_Name], '?') + CHAR(9)
    + IsNull(A.[Student_Last_Name], '?') + CHAR(9)
    + IsNull(A.[Student_Name_Suffix], '?') + CHAR(9)
    + IsNull(A.[Student_Full_Name], '?') + CHAR(9)
    + IsNull(A.[Student_Preferred_Name], '?') + CHAR(9)
    + IsNull(A.[Student_Sort_Name], '?') + CHAR(9)
    + IsNull(A.[Student_SSN], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Student_Birth_Date]), '?') + CHAR(9)
    + IsNull(A.[Student_Birth_Year_Month], '?') + CHAR(9)
    + IsNull(A.[Student_Birth_Year], '?') + CHAR(9)
    + IsNull(A.[Student_Gender_Cd], '?') + CHAR(9)
    + IsNull(A.[Student_Gender_Desc], '?') + CHAR(9)
    + IsNull(A.[Race_Desc], '?') + CHAR(9)
    + IsNull(A.[Federal_Race_Ethnicity_Desc], '?') + CHAR(9)
    )), -- T1C hash key

    -- Type 2 Field Hash
    -- No T2 Fields Found

    -- Type 12 (Update with T2 band) Field Hash
    -- No T12 Fields Found

    -- Foreign Key Columns
    -- No Foreign Keys Found

    -- All Conform Table Columns
    [Local_Student_Id]=A.[Local_Student_Id],
    [Student_Unique_Id]=A.[Student_Unique_Id],
    [Student_State_Id_Nbr]=A.[Student_State_Id_Nbr],
    [Student_Current_Enrolled_Ind]=A.[Student_Current_Enrolled_Ind],
    [Student_First_Name]=A.[Student_First_Name],
    [Student_Middle_Name]=A.[Student_Middle_Name],
    [Student_Last_Name]=A.[Student_Last_Name],
    [Student_Name_Suffix]=A.[Student_Name_Suffix],
    [Student_Full_Name]=A.[Student_Full_Name],
    [Student_Preferred_Name]=A.[Student_Preferred_Name],
    [Student_Sort_Name]=A.[Student_Sort_Name],
    [Student_SSN]=A.[Student_SSN],
    [Student_Birth_Date]=A.[Student_Birth_Date],
    [Student_Birth_Year_Month]=A.[Student_Birth_Year_Month],
    [Student_Birth_Year]=A.[Student_Birth_Year],
    [Student_Birth_Country_Cd]=A.[Student_Birth_Country_Cd],
    [Student_Birth_Country_Name]=A.[Student_Birth_Country_Name],
    [Student_Gender_Cd]=A.[Student_Gender_Cd],
    [Student_Gender_Desc]=A.[Student_Gender_Desc],
    [Student_Gender_Sort_Order]=A.[Student_Gender_Sort_Order],
    [American_Indian_Or_Alaska_Native_Ind]=A.[American_Indian_Or_Alaska_Native_Ind],
    [Asian_Ind]=A.[Asian_Ind],
    [Black_Or_African_American_Ind]=A.[Black_Or_African_American_Ind],
    [Native_Hawaiian_Or_Other_Pacific_Islander_Ind]=A.[Native_Hawaiian_Or_Other_Pacific_Islander_Ind],
    [White_Ind]=A.[White_Ind],
    [Hispanic_Latino_Ind]=A.[Hispanic_Latino_Ind],
    [Hispanic_Latino_Desc]=A.[Hispanic_Latino_Desc],
    [Race_Desc]=A.[Race_Desc],
    [Federal_Race_Ethnicity_Desc]=A.[Federal_Race_Ethnicity_Desc],
    [Number_Of_Races_Reported]=A.[Number_Of_Races_Reported],
    [Student_Immigrant_Ind]=A.[Student_Immigrant_Ind],
    [Student_Migrant_Ind]=A.[Student_Migrant_Ind],
    [Student_Refugee_Ind]=A.[Student_Refugee_Ind],
    [Student_Current_LEP_Ind]=A.[Student_Current_LEP_Ind],
    [Student_Current_Grade_Level_Cd]=A.[Student_Current_Grade_Level_Cd],
    [Student_Current_Grade_Level_Desc]=A.[Student_Current_Grade_Level_Desc],
    [Student_Current_Grade_Level_Sort_Order]=A.[Student_Current_Grade_Level_Sort_Order],
    [Student_Current_State_Grade_Level_Cd]=A.[Student_Current_State_Grade_Level_Cd],
    [Student_Current_State_Grade_Level_Desc]=A.[Student_Current_State_Grade_Level_Desc],
    [Student_Current_State_Grade_Level_Sort_Order]=A.[Student_Current_State_Grade_Level_Sort_Order],
    [Student_Current_Economically_Disadvantaged_Ind]=A.[Student_Current_Economically_Disadvantaged_Ind],
    [Student_Current_Free_Reduced_Meal_Cd]=A.[Student_Current_Free_Reduced_Meal_Cd],
    [Student_Current_Free_Reduced_Meal_Desc]=A.[Student_Current_Free_Reduced_Meal_Desc],
    [Student_Current_Free_Reduced_Meal_Sort_Order]=A.[Student_Current_Free_Reduced_Meal_Sort_Order],
    [Student_Current_Disability_Ind]=A.[Student_Current_Disability_Ind],
    [Student_Date_Entered_District]=A.[Student_Date_Entered_District],
    [Student_Date_Entered_USA_School]=A.[Student_Date_Entered_USA_School],
    [Student_Resident_District]=A.[Student_Resident_District],
    [Student_Citizenship_Country]=A.[Student_Citizenship_Country],
    [Student_USA_Date_Of_Entry]=A.[Student_USA_Date_Of_Entry],
    [Student_Primary_Language]=A.[Student_Primary_Language],
    [Student_Year_Entered_9th_Grade]=A.[Student_Year_Entered_9th_Grade],
    [Student_Graduation_Ind]=A.[Student_Graduation_Ind],
    [Student_Graduation_Date]=A.[Student_Graduation_Date],
    [Student_Diploma_Type_Cd]=A.[Student_Diploma_Type_Cd],
    [Student_Received_Ged_Ind]=A.[Student_Received_Ged_Ind],
    [Student_Current_Title_1_Cd]=A.[Student_Current_Title_1_Cd],
    [Student_Current_Homeless_Ind]=A.[Student_Current_Homeless_Ind],
    [Student_Homeless_Unaccompanied_Youth_Ind]=A.[Student_Homeless_Unaccompanied_Youth_Ind],
    [Student_Current_SpEd_Eligible_Ind]=A.[Student_Current_SpEd_Eligible_Ind],
    [Student_Current_SpEd_Receiving_Ind]=A.[Student_Current_SpEd_Receiving_Ind],
    [Student_SpEd_Area_of_Exceptionality]=A.[Student_SpEd_Area_of_Exceptionality],
    [Student_State_Funding_Type]=A.[Student_State_Funding_Type],
    [Student_Current_Gifted_Ind]=A.[Student_Current_Gifted_Ind],
    [Current_School_Id]=A.[Current_School_Id],
    [Current_School_Name]=A.[Current_School_Name],
    [Batch_Period]=A.[Batch_Period],
    [SAID]=A.[SAID],
    [Date_Stamp]=A.[Date_Stamp],

    OES_Litho=Row_Number() OVER (ORDER BY (SELECT 1))
FROM [conform].[dim_Student] A (NOLOCK)

),

DataMerge AS (
SELECT
    [MissingBusinessKey]=CASE WHEN sd.[Local_Student_Id] IS NULL THEN 1 ELSE 0 END,
    [MissingForeignKey]=0,
    [DupCount]=Row_Number() OVER(partition BY sd.[Local_Student_Id] ORDER BY sd.[Date_Stamp] DESC),
    [Student_Key_Temp]=k1.[Student_Key],
    [Student_Sequence]=IsNull(K1.[Student_Sequence]+1,1),
    [UpdateFlag]=CASE WHEN sd.[Hash_Key_T1] != k1.[Hash_Key_T1] THEN 1 ELSE 0 END,
    [NewSeqFlag]=CASE WHEN sd.[Hash_Key_T1C] != k1.[Hash_Key_T1C] THEN 1 ELSE 0 END,
    [NewKeyFlag]=0,
    [NewRowFlag]=CASE WHEN k1.[Student_Key] IS NULL THEN 1 ELSE 0 END,
    sd.*
FROM StageData sd
left outer join [tdw].[dim_Student] K1
    on sd.[Hash_Key_BK] = K1.[Hash_Key_BK] and K1.Current_Record_Ind='Y'

)

SELECT *,
    [Student_Key]=dm.[Student_Key_Temp],
    [DISCARDFLAG]=CASE WHEN [MissingForeignKey] = 1 OR [MissingBusinessKey] = 1 OR [DUPCOUNT] > 1 THEN 1 ELSE 0 END
FROM DataMerge dm
WHERE [NewRowFlag] = 1 --New Entity
   OR [NewKeyFlag] = 1 --New ADW Key (T2)
   OR [NewSeqFlag] = 1 --New Sequence (T1C)
   OR [UpdateFlag] = 1 --T1 Update
   OR [MissingBusinessKey] = 1 OR [DupCount] > 1 OR [MissingForeignKey] = 1 --Discard Record