/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_fct_Student_Program_Participation_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_fct_Student_Program_Participation_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-15 18:11:01
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_fct_Student_Program_Participation_edfi] @SAID='all', @Batch_Period_List='2018'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="fct_Student_Program_Participation"> 

--<MappingInfoCommon>
declare @ActiveSchoolYear int = (select top 1 SchoolYear from edfi.SchoolYearType where CurrentSchoolYear=1)
--</MappingInfoCommon>

select
     [Academic_Year_Name]=convert(Char(9),
    --<MappingInfoStatus Status="C" Column="Academic_Year_Name">
    convert(varchar,IsNull([edfi].[StudentSchoolAssociation].SchoolYear,@ActiveSchoolYear)-1) 
	+ '-'+ 
	convert(varchar,IsNull([edfi].[StudentSchoolAssociation].SchoolYear,@ActiveSchoolYear))
    --</MappingInfoStatus>
    )

    ,[District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="District_Id">
    [edfi].[StudentProgramAssociation].ProgramEducationOrganizationId
    --</MappingInfoStatus>
    )

    ,[School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Program_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Program_Cd">
    [edfi].[Program].ProgramId
    --</MappingInfoStatus>
    )

    ,[Local_Student_Id]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Local_Student_Id">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[StudentEducationOrganizationAssociationStudentIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.StudentIdentificationSystemDescriptorId
	 where d.CodeValue='Local'
	   and ic.StudentUSI=[edfi].[StudentProgramAssociation].StudentUSI
	),'')
    --</MappingInfoStatus>
    )

    ,[Effective-Date_Of_Day]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Effective-Date_Of_Day">
    [edfi].[StudentProgramAssociation].BeginDate
    --</MappingInfoStatus>
    )

    ,[Ending-Date_Of_Day]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Ending-Date_Of_Day">
    '9999-12-31'  -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[Occurrence]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Occurrence">
    1
    --</MappingInfoStatus>
    )

    ,[Effective_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Effective_Date">
    [edfi].[StudentProgramAssociation].BeginDate
    --</MappingInfoStatus>
    )

    ,[Ending_Date]=convert(Date,
    --<MappingInfoStatus Status="H" Column="Ending_Date">
    '9999-12-31'  -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    IsNull([edfi].[StudentSchoolAssociation].SchoolYear,@ActiveSchoolYear)
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[StudentProgramAssociation].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    getdate()
    --</MappingInfoStatus>
    )

    ,[SourceIdentifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="I" Column="SourceIdentifier">
    0  -- Not found in EdFi
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom>
  from [edfi].[StudentProgramAssociation]
  join [edfi].[Program]
    on [edfi].[Program].ProgramName=[edfi].[StudentProgramAssociation].ProgramName
   and [edfi].[Program].EducationOrganizationId=[edfi].[StudentProgramAssociation].EducationOrganizationId
  join [edfi].[StudentSchoolAssociation]
    on [edfi].[StudentSchoolAssociation].StudentUSI=[edfi].[StudentProgramAssociation].StudentUSI
  join [edfi].[School]
    on [edfi].[School].SchoolId=[edfi].[StudentSchoolAssociation].SchoolId 
   and [edfi].[School].LocalEducationAgencyId=[edfi].[StudentProgramAssociation].ProgramEducationOrganizationId

 where (@Batch_Period_List='all' or IsNull([edfi].[StudentSchoolAssociation].SchoolYear,@ActiveSchoolYear) in (select Batch_Period from @BPLtable))
   and (IsNull(@SAID,'all') in ('all','any') or [edfi].[StudentProgramAssociation].SAID in (select SAID from @SAIDtable)) 
  --</MappingInfoFrom>
--</MappingInfo>