/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_fct_Student_Course_Schedule_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_fct_Student_Course_Schedule_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-15 18:11:01
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_fct_Student_Course_Schedule_edfi] @SAID='all', @Batch_Period_List='all'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="fct_Student_Course_Schedule"> 

--<MappingInfoCommon>

--</MappingInfoCommon>

select
     [Academic_Year_Name]=convert(Char(9),
    --<MappingInfoStatus Status="C" Column="Academic_Year_Name">
    convert(varchar,[edfi].[StudentSectionAssociation].SchoolYear-1) + '-'+ convert(varchar,[edfi].[StudentSectionAssociation].SchoolYear)
    --</MappingInfoStatus>
    )

    ,[District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="District_Id">
    [edfi].[School].LocalEducationAgencyId
    --</MappingInfoStatus>
    )

    ,[Calendar_Track_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Calendar_Track_Cd">
    IsNull([edfi].[StudentSchoolAssociation].CalendarCode,(
	select top (1) CalendarCode 
	  from [edfi].[Calendar] cal
	 where cal.SchoolId=[edfi].[StudentSectionAssociation].SchoolId
	   and cal.SchoolYear=[edfi].[StudentSectionAssociation].SchoolYear
	))
    --</MappingInfoStatus>
    )

    ,[Calendar_Track_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Calendar_Track_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Term_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Term_Cd">
    IsNull((
	select top(1) d.CodeValue
	  from [edfi].[Session] x
	  join [edfi].[Descriptor] d on d.DescriptorId=x.TermDescriptorId
	 where x.SchoolId=[edfi].[StudentSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StudentSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StudentSectionAssociation].SessionName
	),'--')
    --</MappingInfoStatus>
    )

    ,[Course_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Course_Cd">
    IsNull((
	select top(1) co.CourseCode
	  FROM [edfi].[Section] x
	  join [edfi].[CourseOffering] co
		on co.SchoolId=x.SchoolId
	   and co.SchoolYear=x.SchoolYear
	   and co.SessionName=x.SessionName
	   and co.LocalCourseCode=x.LocalCourseCode
	 where x.SchoolId=[edfi].[StudentSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StudentSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StudentSectionAssociation].SessionName
	   and x.SectionIdentifier=[edfi].[StudentSectionAssociation].SectionIdentifier
	),'--')
    --</MappingInfoStatus>
    )

    ,[Course_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Course_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Course_Section_Identifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Course_Section_Identifier">
    [edfi].[StudentSectionAssociation].SectionIdentifier
    --</MappingInfoStatus>
    )

    ,[Local_Student_Id]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Local_Student_Id">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[StudentEducationOrganizationAssociationStudentIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.StudentIdentificationSystemDescriptorId
	 where d.CodeValue='Local'
	   and ic.StudentUSI=[edfi].[StudentSectionAssociation].StudentUSI
	),'')
    --</MappingInfoStatus>
    )

    ,[Enrolled-District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Enrolled-District_Id">
    [edfi].[School].LocalEducationAgencyId
    --</MappingInfoStatus>
    )

    ,[Enrolled-School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Enrolled-School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Attending-District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Attending-District_Id">
    [edfi].[School].LocalEducationAgencyId
    --</MappingInfoStatus>
    )

    ,[Attending-School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Attending-School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Cycle_Day_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="H" Column="Cycle_Day_Cd">
    '--' -- Hold till Bell Schedules and Cycle Days (A day, B day) are implemented.
    --</MappingInfoStatus>
    )

    ,[Start-Period_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Start-Period_Cd">
    IsNull((
	select top(1) x.ClassPeriodName
	  from [edfi].[SectionClassPeriod] x
	 where x.SchoolId=[edfi].[StudentSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StudentSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StudentSectionAssociation].SessionName
	),'--')
    --</MappingInfoStatus>
    )

    ,[Start-Period_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Start-Period_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[End-Period_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="End-Period_Cd">
    IsNull((
	select top(1) x.ClassPeriodName
	  from [edfi].[SectionClassPeriod] x
	 where x.SchoolId=[edfi].[StudentSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StudentSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StudentSectionAssociation].SessionName
	),'--')
    --</MappingInfoStatus>
    )

    ,[End-Period_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="End-Period_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Entered-Date_Of_Day]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Entered-Date_Of_Day">
    [edfi].[StudentSectionAssociation].BeginDate
    --</MappingInfoStatus>
    )

    ,[Exited-Date_Of_Day]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Exited-Date_Of_Day">
    [edfi].[StudentSectionAssociation].EndDate
    --</MappingInfoStatus>
    )

    ,[Entered_Calendar_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Entered_Calendar_Date">
    [edfi].[StudentSectionAssociation].BeginDate
    --</MappingInfoStatus>
    )

    ,[Exited_Calendar_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Exited_Calendar_Date">
    [edfi].[StudentSectionAssociation].EndDate
    --</MappingInfoStatus>
    )

    ,[Course_Enroll_Count]=convert(Decimal(9,2),
    --<MappingInfoStatus Status="C" Column="Course_Enroll_Count">
    1
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    [edfi].[StudentSectionAssociation].SchoolYear
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[StudentSectionAssociation].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    [edfi].[StudentSectionAssociation].LastModifiedDate
    --</MappingInfoStatus>
    )

    ,[SourceIdentifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="SourceIdentifier">
    [edfi].[StudentSectionAssociation].Id
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom> 
  from [edfi].[StudentSectionAssociation]
  join [edfi].[School] on [edfi].[School].SchoolId=[edfi].[StudentSectionAssociation].SchoolId
  join [edfi].[StudentSchoolAssociation]
    on [edfi].[StudentSchoolAssociation].SchoolId=[edfi].[StudentSectionAssociation].SchoolId
   and [edfi].[StudentSchoolAssociation].StudentUSI=[edfi].[StudentSectionAssociation].StudentUSI

  where @Batch_Period_List='all' or [edfi].[StudentSectionAssociation].SchoolYear in (select Batch_Period from @BPLtable)
    and (IsNull(@SAID,'all') in ('all','any') or [edfi].[StudentSectionAssociation].SAID in (select SAID from @SAIDtable) )
  --</MappingInfoFrom>
--</MappingInfo>