/****** Object:  StoredProcedure [dbo].[sp_iMart_Load_dim_School]    Script Date: 4:40:40 PM ******/
CREATE PROCEDURE [dbo].[sp_iMart_Load_dim_School]
AS

-- ============================================================================
-- Script UTC date: 2019-04-22 13:59:06
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example: EXEC [dbo].[sp_iMart_Load_dim_School]

WITH StageData
AS (
SELECT
    -- Business Id (Concatenate Context and all Business Keys)
    -- Business Id deprecated

    -- Natural Key
    [HASH_KEY_BK]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[District_Id], '?') + CHAR(9)
    + IsNull(A.[School_Id], '?') + CHAR(9)
    )), -- BK hash key

    -- Type 1 Field Hash
    [HASH_KEY_T1]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[School_Name], '?') + CHAR(9)
    + IsNull(A.[School_Grade_Cd_Low], '?') + CHAR(9)
    + IsNull(A.[School_Grade_Cd_High], '?') + CHAR(9)
    + IsNull(A.[School_Principal_Name], '?') + CHAR(9)
    + IsNull(A.[School_Level_Cd], '?') + CHAR(9)
    + IsNull(A.[School_Level_Name], '?') + CHAR(9)
    + IsNull(A.[School_Level_Desc], '?') + CHAR(9)
    + IsNull(A.[NCES_School_Type_Cd], '?') + CHAR(9)
    + IsNull(A.[NCES_School_Type_Name], '?') + CHAR(9)
    + IsNull(A.[NCES_School_Type_Desc], '?') + CHAR(9)
    + IsNull(A.[School_Type_Cd], '?') + CHAR(9)
    + IsNull(A.[School_Type_Name], '?') + CHAR(9)
    + IsNull(A.[School_Type_Desc], '?') + CHAR(9)
    + IsNull(A.[School_State_Cd], '?') + CHAR(9)
    + IsNull(A.[School_Local_Cd], '?') + CHAR(9)
    + IsNull(A.[School_NCES_Cd], '?') + CHAR(9)
    + IsNull(A.[School_NCES_Name], '?') + CHAR(9)
    + IsNull(A.[School_Sat_School_Cd], '?') + CHAR(9)
    + IsNull(A.[School_Unique_Id], '?') + CHAR(9)
    + IsNull(A.[School_Short_Name], '?') + CHAR(9)
    + IsNull(A.[School_Academic_Year_Began], '?') + CHAR(9)
    + IsNull(A.[School_Academic_Year_Ended], '?') + CHAR(9)
    + IsNull(A.[School_Is_Closed_Ind], '?') + CHAR(9)
    + IsNull(A.[School_Principal_Email], '?') + CHAR(9)
    + IsNull(A.[School_Phone], '?') + CHAR(9)
    + IsNull(A.[School_Address_1], '?') + CHAR(9)
    + IsNull(A.[School_Address_2], '?') + CHAR(9)
    + IsNull(A.[School_City], '?') + CHAR(9)
    + IsNull(A.[School_State], '?') + CHAR(9)
    + IsNull(A.[School_Postal_Cd], '?') + CHAR(9)
    + IsNull(A.[School_Url], '?') + CHAR(9)
    + IsNull(A.[School_Title1_Ind], '?') + CHAR(9)
    + IsNull(A.[School_Title1_Cd], '?') + CHAR(9)
    + IsNull(A.[School_Title1_Desc], '?') + CHAR(9)
    + IsNull(A.[School_Magnet_Ind], '?') + CHAR(9)
    + IsNull(A.[School_Charter_Ind], '?') + CHAR(9)
    + IsNull(A.[School_Accountability_Ind], '?') + CHAR(9)
    + IsNull(A.[School_NCES_Phone], '?') + CHAR(9)
    + IsNull(A.[School_NCES_Grade_Span], '?') + CHAR(9)
    + IsNull(A.[School_NCES_Operational_Status], '?') + CHAR(9)
    + IsNull(A.[School_Special_Assistance_Status], '?') + CHAR(9)
    + IsNull(A.[School_Cpr_Aed_Instruction_Ind], '?') + CHAR(9)
    + IsNull(A.[School_Online_School_Ind], '?') + CHAR(9)
    + IsNull(A.[School_Course_Catalog_Master_List_Name], '?') + CHAR(9)
    + IsNull(A.[School_State_Reported_Ind], '?') + CHAR(9)
    )), -- T1 hash key

    -- Type 1 C (Track Changes with Sequence) Field Hash
    -- No T1C Fields Found

    -- Type 2 Field Hash
    -- No T2 Fields Found

    -- Type 12 (Update with T2 band) Field Hash
    -- No T12 Fields Found

    -- Foreign Key Columns
    -- No Foreign Keys Found

    -- All Conform Table Columns
    [District_Id]=A.[District_Id],
    [School_Id]=A.[School_Id],
    [School_Name]=A.[School_Name],
    [School_Grade_Cd_Low]=A.[School_Grade_Cd_Low],
    [School_Grade_Cd_High]=A.[School_Grade_Cd_High],
    [School_Principal_Name]=A.[School_Principal_Name],
    [School_Level_Cd]=A.[School_Level_Cd],
    [School_Level_Name]=A.[School_Level_Name],
    [School_Level_Desc]=A.[School_Level_Desc],
    [NCES_School_Type_Cd]=A.[NCES_School_Type_Cd],
    [NCES_School_Type_Name]=A.[NCES_School_Type_Name],
    [NCES_School_Type_Desc]=A.[NCES_School_Type_Desc],
    [School_Type_Cd]=A.[School_Type_Cd],
    [School_Type_Name]=A.[School_Type_Name],
    [School_Type_Desc]=A.[School_Type_Desc],
    [School_State_Cd]=A.[School_State_Cd],
    [School_Local_Cd]=A.[School_Local_Cd],
    [School_NCES_Cd]=A.[School_NCES_Cd],
    [School_NCES_Name]=A.[School_NCES_Name],
    [School_Sat_School_Cd]=A.[School_Sat_School_Cd],
    [School_Unique_Id]=A.[School_Unique_Id],
    [School_Short_Name]=A.[School_Short_Name],
    [School_Academic_Year_Began]=A.[School_Academic_Year_Began],
    [School_Academic_Year_Ended]=A.[School_Academic_Year_Ended],
    [School_Is_Closed_Ind]=A.[School_Is_Closed_Ind],
    [School_Principal_Email]=A.[School_Principal_Email],
    [School_Phone]=A.[School_Phone],
    [School_Address_1]=A.[School_Address_1],
    [School_Address_2]=A.[School_Address_2],
    [School_City]=A.[School_City],
    [School_State]=A.[School_State],
    [School_Postal_Cd]=A.[School_Postal_Cd],
    [School_Latitude]=A.[School_Latitude],
    [School_Longitude]=A.[School_Longitude],
    [School_Url]=A.[School_Url],
    [School_Title1_Ind]=A.[School_Title1_Ind],
    [School_Title1_Cd]=A.[School_Title1_Cd],
    [School_Title1_Desc]=A.[School_Title1_Desc],
    [School_Magnet_Ind]=A.[School_Magnet_Ind],
    [School_Charter_Ind]=A.[School_Charter_Ind],
    [School_Accountability_Ind]=A.[School_Accountability_Ind],
    [School_NCES_Phone]=A.[School_NCES_Phone],
    [School_NCES_Grade_Span]=A.[School_NCES_Grade_Span],
    [School_NCES_Operational_Status]=A.[School_NCES_Operational_Status],
    [School_Special_Assistance_Status]=A.[School_Special_Assistance_Status],
    [School_Cpr_Aed_Instruction_Ind]=A.[School_Cpr_Aed_Instruction_Ind],
    [School_Online_School_Ind]=A.[School_Online_School_Ind],
    [School_Course_Catalog_Master_List_Name]=A.[School_Course_Catalog_Master_List_Name],
    [School_State_Reported_Ind]=A.[School_State_Reported_Ind],
    [Batch_Period]=A.[Batch_Period],
    [SAID]=A.[SAID],
    [Date_Stamp]=A.[Date_Stamp],

    OES_Litho=Row_Number() OVER (ORDER BY (SELECT 1))
FROM [conform].[dim_School] A (NOLOCK)

),

DataMerge AS (
SELECT
    [MissingBusinessKey]=CASE WHEN sd.[District_Id] IS NULL OR sd.[School_Id] IS NULL THEN 1 ELSE 0 END,
    [MissingForeignKey]=0,
    [DupCount]=Row_Number() OVER(partition BY sd.[District_Id], sd.[School_Id] ORDER BY sd.[Date_Stamp] DESC),
    [School_Key_Temp]=k1.[School_Key],
    [UpdateFlag]=CASE WHEN sd.[Hash_Key_T1] != k1.[Hash_Key_T1] THEN 1 ELSE 0 END,
    [NewSeqFlag]=0,
    [NewKeyFlag]=0,
    [NewRowFlag]=CASE WHEN k1.[School_Key] IS NULL THEN 1 ELSE 0 END,
    sd.*
FROM StageData sd
left outer join [tdw].[dim_School] K1
    on sd.[Hash_Key_BK] = K1.[Hash_Key_BK]

)

SELECT *,
    [School_Key]=dm.[School_Key_Temp],
    [DISCARDFLAG]=CASE WHEN [MissingForeignKey] = 1 OR [MissingBusinessKey] = 1 OR [DUPCOUNT] > 1 THEN 1 ELSE 0 END
FROM DataMerge dm
WHERE [NewRowFlag] = 1 --New Entity
   OR [NewKeyFlag] = 1 --New ADW Key (T2)
   OR [NewSeqFlag] = 1 --New Sequence (T1C)
   OR [UpdateFlag] = 1 --T1 Update
   OR [MissingBusinessKey] = 1 OR [DupCount] > 1 OR [MissingForeignKey] = 1 --Discard Record