/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_fct_Student_Course_Grade_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_fct_Student_Course_Grade_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-15 18:11:01
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_fct_Student_Course_Grade_edfi] @SAID='all', @Batch_Period_List='all'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="fct_Student_Course_Grade"> 

--<MappingInfoCommon>

--</MappingInfoCommon>

select
     [Academic_Year_Name]=convert(Char(9),
    --<MappingInfoStatus Status="C" Column="Academic_Year_Name">
    convert(varchar,[edfi].[Grade].SchoolYear-1) 
	+ '-'+ 
	convert(varchar,[edfi].[Grade].SchoolYear)
    --</MappingInfoStatus>
    )

    ,[District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="District_Id">
    [edfi].[School].LocalEducationAgencyId
    --</MappingInfoStatus>
    )

    ,[School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Calendar_Track_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Calendar_Track_Cd">
    IsNull([edfi].[StudentSchoolAssociation].CalendarCode,(
	select top (1) CalendarCode 
	  from [edfi].[Calendar] cal
	 where cal.SchoolId=[edfi].[Grade].SchoolId
	   and cal.SchoolYear=[edfi].[Grade].SchoolYear
	))
    --</MappingInfoStatus>
    )

    ,[Calendar_Track_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Calendar_Track_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Term_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Term_Cd">
    IsNull((
	select top(1) d.CodeValue
	  from [edfi].[Session] x
	  join [edfi].[Descriptor] d on d.DescriptorId=x.TermDescriptorId
	 where x.SchoolId=[edfi].[Grade].SchoolId
	   and x.SchoolYear=[edfi].[Grade].SchoolYear
	   and x.SessionName=[edfi].[Grade].SessionName
	),'--')
    --</MappingInfoStatus>
    )

    ,[Marking_Period_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Marking_Period_Cd">
    IsNull((
	select top (1) d.CodeValue
	  from [edfi].[Descriptor] d 
	 where d.DescriptorId=[edfi].[Grade].GradingPeriodDescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[Grade_Type_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Grade_Type_Cd">
    IsNull((
	select top (1) d.CodeValue
	  from [edfi].[Descriptor] d 
	 where d.DescriptorId=[edfi].[Grade].GradeTypeDescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[Course_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Course_Cd">
    IsNull((
	select top(1) co.CourseCode
	  FROM [edfi].[Section] x
	  join [edfi].[CourseOffering] co
		on co.SchoolId=x.SchoolId
	   and co.SchoolYear=x.SchoolYear
	   and co.SessionName=x.SessionName
	   and co.LocalCourseCode=x.LocalCourseCode
	 where x.SchoolId=[edfi].[Grade].SchoolId
	   and x.SchoolYear=[edfi].[Grade].SchoolYear
	   and x.SessionName=[edfi].[Grade].SessionName
	   and x.SectionIdentifier=[edfi].[Grade].SectionIdentifier
	),'--')
    --</MappingInfoStatus>
    )

    ,[Course_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Course_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Course_Section_Identifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Course_Section_Identifier">
    [edfi].[Grade].SectionIdentifier
    --</MappingInfoStatus>
    )

    ,[Local_Student_Id]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Local_Student_Id">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[StudentEducationOrganizationAssociationStudentIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.StudentIdentificationSystemDescriptorId
	 where d.CodeValue='Local'
	   and ic.StudentUSI=[edfi].[Grade].StudentUSI
	),'')
    --</MappingInfoStatus>
    )

    ,[Letter_Grade]=convert(VarChar(12),
    --<MappingInfoStatus Status="C" Column="Letter_Grade">
    [edfi].[Grade].LetterGradeEarned
    --</MappingInfoStatus>
    )

    ,[Numeric_Grade]=convert(Decimal(9,2),
    --<MappingInfoStatus Status="C" Column="Numeric_Grade">
    [edfi].[Grade].NumericGradeEarned
    --</MappingInfoStatus>
    )

    ,[Grade_Point_Max]=convert(Decimal(9,2),
    --<MappingInfoStatus Status="H" Column="Grade_Point_Max">
    0.0 -- Not Found in EdFi
    --</MappingInfoStatus>
    )

    ,[Passing_Grade_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="H" Column="Passing_Grade_Ind">
    '-' -- Not Found in EdFi
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    [edfi].[Grade].SchoolYear
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[Grade].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    [edfi].[Grade].LastModifiedDate
    --</MappingInfoStatus>
    )

    ,[SourceIdentifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="SourceIdentifier">
    [edfi].[Grade].id
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom>  -- select count(*)
  from [edfi].[Grade]
  join [edfi].[School] on [edfi].[School].SchoolId=[edfi].[Grade].SchoolId
  join [edfi].[StudentSchoolAssociation]
    on [edfi].[StudentSchoolAssociation].SchoolId=[edfi].[Grade].SchoolId
   and [edfi].[StudentSchoolAssociation].StudentUSI=[edfi].[Grade].StudentUSI
   -- and [edfi].[StudentSchoolAssociation].SchoolYear=[edfi].[Grade].SchoolYear

 where (@Batch_Period_List='all' or [edfi].[Grade].SchoolYear in (select Batch_Period from @BPLtable))
   and (IsNull(@SAID,'all') in ('all','any') or [edfi].[Grade].SAID in (select SAID from @SAIDtable) )
  --</MappingInfoFrom>
--</MappingInfo>