/****** Object:  StoredProcedure [dbo].[sp_iMart_Load_dim_Date]    Script Date: 4:40:40 PM ******/
CREATE PROCEDURE [dbo].[sp_iMart_Load_dim_Date]
AS

-- ============================================================================
-- Script UTC date: 2019-04-22 13:59:06
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example: EXEC [dbo].[sp_iMart_Load_dim_Date]

WITH StageData
AS (
SELECT
    -- Business Id (Concatenate Context and all Business Keys)
    -- Business Id deprecated

    -- Natural Key
    [HASH_KEY_BK]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(CONVERT(VARCHAR, A.[Date_Of_Day]), '?') + CHAR(9)
    )), -- BK hash key

    -- Type 1 Field Hash
    [HASH_KEY_T1]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[Date_Record_Type], '?') + CHAR(9)
    + IsNull(A.[Year_Name], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Year_Number_Sequence]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Year_Begin_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Year_End_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Days_In_Year]), '?') + CHAR(9)
    + IsNull(A.[Quarter_Name], '?') + CHAR(9)
    + IsNull(A.[Year_Quarter_Name], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Quarter_Number_In_Year]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Quarter_Number_Sequence]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Quarter_Begin_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Quarter_End_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Days_In_Quarter]), '?') + CHAR(9)
    + IsNull(A.[Month_Name], '?') + CHAR(9)
    + IsNull(A.[Month_Year_Name], '?') + CHAR(9)
    + IsNull(A.[Year_Month_Yyyy_Mm], '?') + CHAR(9)
    + IsNull(A.[Month_Abbr], '?') + CHAR(9)
    + IsNull(A.[Month_Year_Abbr], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Month_Number_In_Year]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Month_Number_In_Quarter]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Month_Number_Sequence]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Month_Begin_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Month_End_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Days_In_Month]), '?') + CHAR(9)
    + IsNull(A.[Week_Name], '?') + CHAR(9)
    + IsNull(A.[Week_Abbr], '?') + CHAR(9)
    + IsNull(A.[Year_Week_Name], '?') + CHAR(9)
    + IsNull(A.[Year_Week_Abbr], '?') + CHAR(9)
    + IsNull(A.[Week_Desc_Short], '?') + CHAR(9)
    + IsNull(A.[Week_Desc], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Week_Begin_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Week_End_Date]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Week_Number_In_Year]), '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Week_Number_Sequence]), '?') + CHAR(9)
    + IsNull(A.[Date_String], '?') + CHAR(9)
    + IsNull(A.[Date_Desc], '?') + CHAR(9)
    + IsNull(A.[Date_Desc_Short], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Day_Number_In_Year]), '?') + CHAR(9)
    + IsNull(A.[First_Day_In_Year_Ind], '?') + CHAR(9)
    + IsNull(A.[Last_Day_In_Year_Ind], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Day_Number_In_Quarter]), '?') + CHAR(9)
    + IsNull(A.[First_Day_In_Quarter_Ind], '?') + CHAR(9)
    + IsNull(A.[Last_Day_In_Quarter_Ind], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Day_Number_In_Month]), '?') + CHAR(9)
    + IsNull(A.[First_Day_In_Month_Ind], '?') + CHAR(9)
    + IsNull(A.[Last_Day_In_Month_Ind], '?') + CHAR(9)
    + IsNull(A.[Weekday_Name], '?') + CHAR(9)
    + IsNull(A.[Weekday_Abbr], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Day_Number_In_Week]), '?') + CHAR(9)
    + IsNull(A.[First_Day_In_Week_Ind], '?') + CHAR(9)
    + IsNull(A.[Last_Day_In_Week_Ind], '?') + CHAR(9)
    + IsNull(CONVERT(VARCHAR, A.[Day_Number_Sequence]), '?') + CHAR(9)
    + IsNull(A.[Weekday_Ind], '?') + CHAR(9)
    )), -- T1 hash key

    -- Type 1 C (Track Changes with Sequence) Field Hash
    -- No T1C Fields Found

    -- Type 2 Field Hash
    -- No T2 Fields Found

    -- Type 12 (Update with T2 band) Field Hash
    -- No T12 Fields Found

    -- Foreign Key Columns
    -- No Foreign Keys Found

    -- All Conform Table Columns
    [Date_Record_Type]=A.[Date_Record_Type],
    [Year_Name]=A.[Year_Name],
    [Year_Number_Sequence]=A.[Year_Number_Sequence],
    [Year_Begin_Date]=A.[Year_Begin_Date],
    [Year_End_Date]=A.[Year_End_Date],
    [Days_In_Year]=A.[Days_In_Year],
    [Quarter_Name]=A.[Quarter_Name],
    [Year_Quarter_Name]=A.[Year_Quarter_Name],
    [Quarter_Number_In_Year]=A.[Quarter_Number_In_Year],
    [Quarter_Number_Sequence]=A.[Quarter_Number_Sequence],
    [Quarter_Begin_Date]=A.[Quarter_Begin_Date],
    [Quarter_End_Date]=A.[Quarter_End_Date],
    [Days_In_Quarter]=A.[Days_In_Quarter],
    [Month_Name]=A.[Month_Name],
    [Month_Year_Name]=A.[Month_Year_Name],
    [Year_Month_Yyyy_Mm]=A.[Year_Month_Yyyy_Mm],
    [Month_Abbr]=A.[Month_Abbr],
    [Month_Year_Abbr]=A.[Month_Year_Abbr],
    [Month_Number_In_Year]=A.[Month_Number_In_Year],
    [Month_Number_In_Quarter]=A.[Month_Number_In_Quarter],
    [Month_Number_Sequence]=A.[Month_Number_Sequence],
    [Month_Begin_Date]=A.[Month_Begin_Date],
    [Month_End_Date]=A.[Month_End_Date],
    [Days_In_Month]=A.[Days_In_Month],
    [Week_Name]=A.[Week_Name],
    [Week_Abbr]=A.[Week_Abbr],
    [Year_Week_Name]=A.[Year_Week_Name],
    [Year_Week_Abbr]=A.[Year_Week_Abbr],
    [Week_Desc_Short]=A.[Week_Desc_Short],
    [Week_Desc]=A.[Week_Desc],
    [Week_Begin_Date]=A.[Week_Begin_Date],
    [Week_End_Date]=A.[Week_End_Date],
    [Week_Number_In_Year]=A.[Week_Number_In_Year],
    [Week_Number_Sequence]=A.[Week_Number_Sequence],
    [Date_Of_Day]=A.[Date_Of_Day],
    [Date_String]=A.[Date_String],
    [Date_Desc]=A.[Date_Desc],
    [Date_Desc_Short]=A.[Date_Desc_Short],
    [Day_Number_In_Year]=A.[Day_Number_In_Year],
    [First_Day_In_Year_Ind]=A.[First_Day_In_Year_Ind],
    [Last_Day_In_Year_Ind]=A.[Last_Day_In_Year_Ind],
    [Day_Number_In_Quarter]=A.[Day_Number_In_Quarter],
    [First_Day_In_Quarter_Ind]=A.[First_Day_In_Quarter_Ind],
    [Last_Day_In_Quarter_Ind]=A.[Last_Day_In_Quarter_Ind],
    [Day_Number_In_Month]=A.[Day_Number_In_Month],
    [First_Day_In_Month_Ind]=A.[First_Day_In_Month_Ind],
    [Last_Day_In_Month_Ind]=A.[Last_Day_In_Month_Ind],
    [Weekday_Name]=A.[Weekday_Name],
    [Weekday_Abbr]=A.[Weekday_Abbr],
    [Day_Number_In_Week]=A.[Day_Number_In_Week],
    [First_Day_In_Week_Ind]=A.[First_Day_In_Week_Ind],
    [Last_Day_In_Week_Ind]=A.[Last_Day_In_Week_Ind],
    [Day_Number_Sequence]=A.[Day_Number_Sequence],
    [Weekday_Ind]=A.[Weekday_Ind],
    [Batch_Period]=A.[Batch_Period],
    [SAID]=A.[SAID],
    [Date_Stamp]=A.[Date_Stamp],

    OES_Litho=Row_Number() OVER (ORDER BY (SELECT 1))
FROM [conform].[dim_Date] A (NOLOCK)

),

DataMerge AS (
SELECT
    [MissingBusinessKey]=CASE WHEN sd.[Date_Of_Day] IS NULL THEN 1 ELSE 0 END,
    [MissingForeignKey]=0,
    [DupCount]=Row_Number() OVER(partition BY sd.[Date_Of_Day] ORDER BY sd.[Date_Stamp] DESC),
    [Date_Key_Temp]=k1.[Date_Key],
    [UpdateFlag]=CASE WHEN sd.[Hash_Key_T1] != k1.[Hash_Key_T1] THEN 1 ELSE 0 END,
    [NewSeqFlag]=0,
    [NewKeyFlag]=0,
    [NewRowFlag]=CASE WHEN k1.[Date_Key] IS NULL THEN 1 ELSE 0 END,
    sd.*
FROM StageData sd
left outer join [tdw].[dim_Date] K1
    on sd.[Hash_Key_BK] = K1.[Hash_Key_BK]

)

SELECT *,
    [Date_Key]=dm.[Date_Key_Temp],
    [DISCARDFLAG]=CASE WHEN [MissingForeignKey] = 1 OR [MissingBusinessKey] = 1 OR [DUPCOUNT] > 1 THEN 1 ELSE 0 END
FROM DataMerge dm
WHERE [NewRowFlag] = 1 --New Entity
   OR [NewKeyFlag] = 1 --New ADW Key (T2)
   OR [NewSeqFlag] = 1 --New Sequence (T1C)
   OR [UpdateFlag] = 1 --T1 Update
   OR [MissingBusinessKey] = 1 OR [DupCount] > 1 OR [MissingForeignKey] = 1 --Discard Record