/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_fct_Teacher_Course_Schedule_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_fct_Teacher_Course_Schedule_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-15 18:11:01
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_fct_Teacher_Course_Schedule_edfi] @SAID='all', @Batch_Period_List='all'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="fct_Teacher_Course_Schedule"> 

--<MappingInfoCommon/>

select
     [Academic_Year_Name]=convert(Char(9),
    --<MappingInfoStatus Status="C" Column="Academic_Year_Name">
    convert(varchar,[edfi].[StaffSectionAssociation].SchoolYear-1) + '-'+ convert(varchar,[edfi].[StaffSectionAssociation].SchoolYear)
    --</MappingInfoStatus>
    )

    ,[District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="District_Id">
    [edfi].[School].LocalEducationAgencyId
    --</MappingInfoStatus>
    )

    ,[Calendar_Track_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Calendar_Track_Cd">
    IsNull([edfi].[StaffSchoolAssociation].CalendarCode,(
	select top (1) CalendarCode 
	  from [edfi].[Calendar] cal
	 where cal.SchoolId=[edfi].[StaffSectionAssociation].SchoolId
	   and cal.SchoolYear=[edfi].[StaffSectionAssociation].SchoolYear
	))
    --</MappingInfoStatus>
    )

    ,[Calendar_Track_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Calendar_Track_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Term_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Term_Cd">
    IsNull((
	select top(1) d.CodeValue
	  from [edfi].[Session] x
	  join [edfi].[Descriptor] d on d.DescriptorId=x.TermDescriptorId
	 where x.SchoolId=[edfi].[StaffSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StaffSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StaffSectionAssociation].SessionName
	),'--')
    --</MappingInfoStatus>
    )

    ,[Course_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Course_Cd">
    IsNull((
	select top(1) co.CourseCode
	  FROM [edfi].[Section] x
	  join [edfi].[CourseOffering] co
		on co.SchoolId=x.SchoolId
	   and co.SchoolYear=x.SchoolYear
	   and co.SessionName=x.SessionName
	   and co.LocalCourseCode=x.LocalCourseCode
	 where x.SchoolId=[edfi].[StaffSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StaffSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StaffSectionAssociation].SessionName
	   and x.SectionIdentifier=[edfi].[StaffSectionAssociation].SectionIdentifier
	),'--')

    --</MappingInfoStatus>
    )

    ,[Course_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Course_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Course_Section_Identifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Course_Section_Identifier">
    [edfi].[StaffSectionAssociation].SectionIdentifier
    --</MappingInfoStatus>
    )

    ,[Local_Staff_Id]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Local_Staff_Id">
    IsNull((
	select top (1) s.StaffUniqueId
	  from [edfi].[Staff] s
	 where s.StaffUSI=[edfi].[StaffSectionAssociation].StaffUSI
	),'')
    --</MappingInfoStatus>
    )

    ,[School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Id">
    [edfi].[StaffSectionAssociation].SchoolId
    --</MappingInfoStatus>
    )

    ,[Cycle_Day_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="H" Column="Cycle_Day_Cd">
    '--' -- Hold till Bell Schedules and Cycle Days (A day, B day) are implemented.
    --</MappingInfoStatus>
    )

    ,[Start-Period_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Start-Period_Cd">
    IsNull((
	select top(1) x.ClassPeriodName
	  from [edfi].[SectionClassPeriod] x
	 where x.SchoolId=[edfi].[StaffSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StaffSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StaffSectionAssociation].SessionName
	),'--')
    --</MappingInfoStatus>
    )

    ,[Start-Period_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Start-Period_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[End-Period_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="End-Period_Cd">
    IsNull((
	select top(1) x.ClassPeriodName
	  from [edfi].[SectionClassPeriod] x
	 where x.SchoolId=[edfi].[StaffSectionAssociation].SchoolId
	   and x.SchoolYear=[edfi].[StaffSectionAssociation].SchoolYear
	   and x.SessionName=[edfi].[StaffSectionAssociation].SessionName
	),'--')
    --</MappingInfoStatus>
    )

    ,[End-Period_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="End-Period_School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Entered-Date_Of_Day]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Entered-Date_Of_Day">
    IsNull([edfi].[StaffSectionAssociation].BeginDate,'1753-01-01')
    --</MappingInfoStatus>
    )

    ,[Exited-Date_Of_Day]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Exited-Date_Of_Day">
    IsNull([edfi].[StaffSectionAssociation].EndDate,'9999-12-31')
    --</MappingInfoStatus>
    )

    ,[Entered_Calendar_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Entered_Calendar_Date">
    IsNull([edfi].[StaffSectionAssociation].BeginDate,'1753-01-01')
    --</MappingInfoStatus>
    )

    ,[Exited_Calendar_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Exited_Calendar_Date">
    IsNull([edfi].[StaffSectionAssociation].EndDate,'9999-12-31')
    --</MappingInfoStatus>
    )

    ,[Course_Enroll_Count]=convert(Decimal(9,2),
    --<MappingInfoStatus Status="C" Column="Course_Enroll_Count">
    1
    --</MappingInfoStatus>
    )

    ,[Primary_Secondary_CD]=convert(Char(2),
    --<MappingInfoStatus Status="C" Column="Primary_Secondary_CD">
    IsNull((
	select top (1) 
	  case when d.CodeValue in ('Preschool/Prekindergarten','Kindergarten','First grade','Second grade','Third grade','Fourth grade','Fifth grade') then 'P'
	       when d.CodeValue in ('Sixth grade','Seventh grade','Eighth grade','Ninth grade','Tenth grade','Eleventh grade','Twelfth grade') then 'S'
		   else '' end
	  from [edfi].[StaffSchoolAssociationGradeLevel] x
	  join [edfi].[Descriptor] d on d.Descriptorid=x.GradeLevelDescriptorId
	 where x.StaffUSI=[edfi].[StaffSectionAssociation].StaffUSI
	   and x.SchoolId=[edfi].[StaffSectionAssociation].SchoolId
	 order by d.DescriptorId
	),'')
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    [edfi].[StaffSectionAssociation].SchoolYear
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[StaffSectionAssociation].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    [edfi].[StaffSectionAssociation].LastModifiedDate
    --</MappingInfoStatus>
    )

    ,[SourceIdentifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="SourceIdentifier">
    [edfi].[StaffSectionAssociation].Id
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom> 
  from [edfi].[StaffSectionAssociation]
  join [edfi].[School] on [edfi].[School].SchoolId=[edfi].[StaffSectionAssociation].SchoolId
  join [edfi].[StaffSchoolAssociation]
    on [edfi].[StaffSchoolAssociation].SchoolId=[edfi].[StaffSectionAssociation].SchoolId
   and [edfi].[StaffSchoolAssociation].StaffUSI=[edfi].[StaffSectionAssociation].StaffUSI

  where @Batch_Period_List='all' or [edfi].[StaffSectionAssociation].SchoolYear in (select Batch_Period from @BPLtable)
    and (IsNull(@SAID,'all') in ('all','any') or [edfi].[StaffSectionAssociation].SAID in (select SAID from @SAIDtable) )
  --</MappingInfoFrom>
--</MappingInfo>