/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_dim_Period_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_dim_Period_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-15 18:11:01
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_dim_Period_edfi] @SAID='all', @Batch_Period_List='all'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="dim_Period"> 

--<MappingInfoCommon>
declare @ActiveSchoolYear int = (select top 1 SchoolYear from edfi.SchoolYearType where CurrentSchoolYear=1)
--</MappingInfoCommon>

select
     [Period_School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="Period_School_Id">
    [edfi].[ClassPeriod].SchoolId
    --</MappingInfoStatus>
    )

    ,[Period_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Period_Cd">
    [edfi].[ClassPeriod].ClassPeriodName
    --</MappingInfoStatus>
    )

    ,[Period_Desc]=convert(VarChar(254),
    --<MappingInfoStatus Status="C" Column="Period_Desc">
    [edfi].[ClassPeriod].ClassPeriodName
    --</MappingInfoStatus>
    )

    ,[Period_Sort_Order]=convert(SmallInt,
    --<MappingInfoStatus Status="I" Column="Period_Sort_Order">
    0 -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[Period_Start_Time]=convert(Time(7),
    --<MappingInfoStatus Status="C" Column="Period_Start_Time">
    IsNull([edfi].[ClassPeriodMeetingTime].StartTime,'12:00:00')
    --</MappingInfoStatus>
    )

    ,[Period_End_Time]=convert(Time(7),
    --<MappingInfoStatus Status="C" Column="Period_End_Time">
    IsNull([edfi].[ClassPeriodMeetingTime].EndTime,'12:00:00')
    --</MappingInfoStatus>
    )

    ,[Period_Noninstructional_Minutes]=convert(SmallInt,
    --<MappingInfoStatus Status="I" Column="Period_Noninstructional_Minutes">
    0 -- Not found in EdFi
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    @ActiveSchoolYear
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[ClassPeriod].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    [edfi].[ClassPeriod].LastModifiedDate
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom> -- select *
  from [edfi].[ClassPeriod]
  left outer
  join [edfi].[ClassPeriodMeetingTime] 
    on [edfi].[ClassPeriodMeetingTime].ClassPeriodName=[edfi].[ClassPeriod].ClassPeriodName
   and [edfi].[ClassPeriodMeetingTime].SchoolId=[edfi].[ClassPeriod].SchoolId

  where @Batch_Period_List='all' or @ActiveSchoolYear in (select Batch_Period from @BPLtable)
    and (IsNull(@SAID,'all') in ('all','any') or [edfi].[ClassPeriod].SAID in (select SAID from @SAIDtable) )
  --</MappingInfoFrom>
--</MappingInfo>