/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_fct_Student_Course_Transcript_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_fct_Student_Course_Transcript_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-22 13:59:06
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_fct_Student_Course_Transcript_edfi] @SAID='all', @Batch_Period_List='all'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="fct_Student_Course_Transcript"> 

--<MappingInfoCommon>
declare @ActiveSchoolYear smallint = (select top (1) SchoolYear from [edfi].[SchoolYearType] where CurrentSchoolYear=1)
--</MappingInfoCommon>

select
     [Academic_Year_Name]=convert(Char(9),
    --<MappingInfoStatus Status="C" Column="Academic_Year_Name">
    convert(varchar,[edfi].[CourseTranscript].SchoolYear-1) 
	+ '-'+ 
	convert(varchar,[edfi].[CourseTranscript].SchoolYear)
    --</MappingInfoStatus>
    )

    ,[District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="District_Id">
    [edfi].[School].LocalEducationAgencyId
    --</MappingInfoStatus>
    )

    ,[School_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="School_Id">
    [edfi].[School].SchoolId
    --</MappingInfoStatus>
    )

    ,[Calendar_Track_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Calendar_Track_Cd">
    IsNull([edfi].[StudentSchoolAssociation].CalendarCode,(
	select top (1) CalendarCode 
	  from [edfi].[Calendar] cal
	 where cal.SchoolId=[edfi].[CourseTranscript].CourseEducationOrganizationId
	   and cal.SchoolYear=[edfi].[CourseTranscript].SchoolYear
	))
    --</MappingInfoStatus>
    )

    ,[Term_Cd]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Term_Cd">
    IsNull((
	select top(1) d.CodeValue
	  from [edfi].[Descriptor] d
	 where d.DescriptorId=[edfi].[CourseTranscript].TermDescriptorId
	),'--')
    --</MappingInfoStatus>
    )

    ,[Local_Student_Id]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Local_Student_Id">
    IsNull((
	select top (1) ic.IdentificationCode
	  from [edfi].[StudentEducationOrganizationAssociationStudentIdentificationCode] ic
	  join [edfi].[Descriptor] d on d.DescriptorId=ic.StudentIdentificationSystemDescriptorId
	 where d.CodeValue='Local'
	   and ic.StudentUSI=[edfi].[CourseTranscript].StudentUSI
	),'')
    --</MappingInfoStatus>
    )

    ,[Letter_Grade]=convert(VarChar(12),
    --<MappingInfoStatus Status="C" Column="Letter_Grade">
    [edfi].[CourseTranscript].FinalLetterGradeEarned
    --</MappingInfoStatus>
    )

    ,[Numeric_Grade]=convert(Decimal(9,2),
    --<MappingInfoStatus Status="C" Column="Numeric_Grade">
    [edfi].[CourseTranscript].FinalNumericGradeEarned
    --</MappingInfoStatus>
    )

    ,[Credit_Attempted]=convert(Decimal(5,2),
    --<MappingInfoStatus Status="C" Column="Credit_Attempted">
    [edfi].[CourseTranscript].AttemptedCredits
    --</MappingInfoStatus>
    )

    ,[Credit_Earned]=convert(Decimal(5,2),
    --<MappingInfoStatus Status="C" Column="Credit_Earned">
    [edfi].[CourseTranscript].EarnedCredits
    --</MappingInfoStatus>
    )

    ,[Quality_Points_Earned]=convert(Decimal(5,2),
    --<MappingInfoStatus Status="H" Column="Quality_Points_Earned">
    0.0 -- Not Found in EdFi
    --</MappingInfoStatus>
    )

    ,[Grade_Point_Max]=convert(Decimal(9,2),
    --<MappingInfoStatus Status="H" Column="Grade_Point_Max">
    0.0 -- Not Found in EdFi
    --</MappingInfoStatus>
    )

    ,[Passing_Grade_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="Passing_Grade_Ind">
    case
	when [edfi].[CourseTranscript].FinalLetterGradeEarned in ('A','B','C','D') then 'Y'
	else 'N' end
    --</MappingInfoStatus>
    )

    ,[Content_Completer_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="H" Column="Content_Completer_Ind">
    '-' -- Not found in EdFi 
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    [edfi].[CourseTranscript].SchoolYear
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[CourseTranscript].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    [edfi].[CourseTranscript].LastModifiedDate
    --</MappingInfoStatus>
    )

    ,[SourceIdentifier]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="SourceIdentifier">
    [edfi].[CourseTranscript].id
    --</MappingInfoStatus>
    )


  --<MappingInfoFrom>  -- select count(*)  -- select top (100) *
  from [edfi].[CourseTranscript]
  join [edfi].[School] on [edfi].[School].SchoolId=[edfi].[CourseTranscript].CourseEducationOrganizationId
  join [edfi].[StudentSchoolAssociation]
    on [edfi].[StudentSchoolAssociation].SchoolId=[edfi].[CourseTranscript].CourseEducationOrganizationId
   and [edfi].[StudentSchoolAssociation].StudentUSI=[edfi].[CourseTranscript].StudentUSI
   and IsNull([edfi].[StudentSchoolAssociation].SchoolYear,@ActiveSchoolYear)=[edfi].[CourseTranscript].SchoolYear
 where (@Batch_Period_List='all' or [edfi].[CourseTranscript].SchoolYear in (select Batch_Period from @BPLtable))
   and (IsNull(@SAID,'all') in ('all','any') or [edfi].[CourseTranscript].SAID in (select SAID from @SAIDtable) )
  --</MappingInfoFrom>
--</MappingInfo>