/****** Object:  StoredProcedure [dbo].[sp_iMart_Load_dim_Course]    Script Date: 4:40:40 PM ******/
CREATE PROCEDURE [dbo].[sp_iMart_Load_dim_Course]
AS

-- ============================================================================
-- Script UTC date: 2019-04-22 13:59:06
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example: EXEC [dbo].[sp_iMart_Load_dim_Course]

WITH StageData
AS (
SELECT
    -- Business Id (Concatenate Context and all Business Keys)
    -- Business Id deprecated

    -- Natural Key
    [HASH_KEY_BK]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[Course_Cd], '?') + CHAR(9)
    )), -- BK hash key

    -- Type 1 Field Hash
    [HASH_KEY_T1]=CONVERT(Binary(16), HASHBYTES('MD5',
    IsNull(A.[Course_Title], '?') + CHAR(9)
    + IsNull(A.[Course_Desc], '?') + CHAR(9)
    + IsNull(A.[Course_State_Cd], '?') + CHAR(9)
    + IsNull(A.[Course_State_Title], '?') + CHAR(9)
    + IsNull(A.[Course_State_Code_Desc], '?') + CHAR(9)
    + IsNull(A.[Course_Department_Desc], '?') + CHAR(9)
    + IsNull(A.[Course_Active_Ind], '?') + CHAR(9)
    + IsNull(A.[Course_Level_Cd], '?') + CHAR(9)
    + IsNull(A.[Advanced_Placement_Cd], '?') + CHAR(9)
    + IsNull(A.[Advanced_Placement_Desc], '?') + CHAR(9)
    + IsNull(A.[SCED_Course_Cd], '?') + CHAR(9)
    + IsNull(A.[SCED_Course_Subject_Cd], '?') + CHAR(9)
    + IsNull(A.[SCED_Course_Sequence], '?') + CHAR(9)
    )), -- T1 hash key

    -- Type 1 C (Track Changes with Sequence) Field Hash
    -- No T1C Fields Found

    -- Type 2 Field Hash
    -- No T2 Fields Found

    -- Type 12 (Update with T2 band) Field Hash
    -- No T12 Fields Found

    -- Foreign Key Columns
    -- No Foreign Keys Found

    -- All Conform Table Columns
    [Course_Cd]=A.[Course_Cd],
    [Course_Title]=A.[Course_Title],
    [Course_Desc]=A.[Course_Desc],
    [Course_State_Cd]=A.[Course_State_Cd],
    [Course_State_Title]=A.[Course_State_Title],
    [Course_State_Code_Desc]=A.[Course_State_Code_Desc],
    [Course_Department_Desc]=A.[Course_Department_Desc],
    [Course_Active_Ind]=A.[Course_Active_Ind],
    [Course_Level_Cd]=A.[Course_Level_Cd],
    [Advanced_Placement_Cd]=A.[Advanced_Placement_Cd],
    [Advanced_Placement_Desc]=A.[Advanced_Placement_Desc],
    [SCED_Course_Cd]=A.[SCED_Course_Cd],
    [SCED_Course_Subject_Cd]=A.[SCED_Course_Subject_Cd],
    [SCED_Course_Sequence]=A.[SCED_Course_Sequence],
    [Batch_Period]=A.[Batch_Period],
    [SAID]=A.[SAID],
    [Date_Stamp]=A.[Date_Stamp],

    OES_Litho=Row_Number() OVER (ORDER BY (SELECT 1))
FROM [conform].[dim_Course] A (NOLOCK)

),

DataMerge AS (
SELECT
    [MissingBusinessKey]=CASE WHEN sd.[Course_Cd] IS NULL THEN 1 ELSE 0 END,
    [MissingForeignKey]=0,
    [DupCount]=Row_Number() OVER(partition BY sd.[Course_Cd] ORDER BY sd.[Date_Stamp] DESC),
    [Course_Key_Temp]=k1.[Course_Key],
    [UpdateFlag]=CASE WHEN sd.[Hash_Key_T1] != k1.[Hash_Key_T1] THEN 1 ELSE 0 END,
    [NewSeqFlag]=0,
    [NewKeyFlag]=0,
    [NewRowFlag]=CASE WHEN k1.[Course_Key] IS NULL THEN 1 ELSE 0 END,
    sd.*
FROM StageData sd
left outer join [tdw].[dim_Course] K1
    on sd.[Hash_Key_BK] = K1.[Hash_Key_BK]

)

SELECT *,
    [Course_Key]=dm.[Course_Key_Temp],
    [DISCARDFLAG]=CASE WHEN [MissingForeignKey] = 1 OR [MissingBusinessKey] = 1 OR [DUPCOUNT] > 1 THEN 1 ELSE 0 END
FROM DataMerge dm
WHERE [NewRowFlag] = 1 --New Entity
   OR [NewKeyFlag] = 1 --New ADW Key (T2)
   OR [NewSeqFlag] = 1 --New Sequence (T1C)
   OR [UpdateFlag] = 1 --T1 Update
   OR [MissingBusinessKey] = 1 OR [DupCount] > 1 OR [MissingForeignKey] = 1 --Discard Record