/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_dim_Date]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_dim_Date]
(
	@BeginDate date = '2001-08-01',
	@nbrYears int = 1
)
as

-- ============================================================================
-- Script UTC date: 2019-03-28 13:35:45
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_DIM_DATE] @BeginDate='2001-01-01', @nbrYears=30
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing

--<MappingInfo Table="dim_Date"> 

--<MappingInfoCommon>
if @BeginDate is null set @BeginDate = '2001-08-01'
if @nbrYears is null set @nbrYears = 1

declare @datetable table ( [date] date, seq int IDENTITY(1,1)) 
declare @loopdate date = @BeginDate
declare @EndDate date = dateadd(YEAR,@nbrYears,@BeginDate)

while @loopdate < @EndDate
begin  
  insert into @datetable ([date]) values (@loopdate)
  set @loopdate=dateadd(day,1,@loopdate)
end 
-- Including Unknown low date and Unknown high date
insert into @datetable ([date]) values ('1753-01-01'),('9999-12-31')
--</MappingInfoCommon>

select
     [Date_Record_Type]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="Date_Record_Type">
    'C'
    --</MappingInfoStatus>
    )

    ,[Year_Name]=convert(Char(4),
    --<MappingInfoStatus Status="C" Column="Year_Name">
    datepart(year,x.date)
    --</MappingInfoStatus>
    )

    ,[Year_Number_Sequence]=convert(Int,
    --<MappingInfoStatus Status="C" Column="Year_Number_Sequence">
    datepart(year,x.date)
    --</MappingInfoStatus>
    )

    ,[Year_Begin_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Year_Begin_Date">
    convert(varchar,datepart(year,x.date)) + '-01-01'
    --</MappingInfoStatus>
    )

    ,[Year_End_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Year_End_Date">
    convert(varchar,datepart(year,x.date)) + '-12-31'
    --</MappingInfoStatus>
    )

    ,[Days_In_Year]=convert(SmallInt,
    --<MappingInfoStatus Status="C" Column="Days_In_Year">
    IIF(DAY(EOMONTH(DATEFROMPARTS(datepart(year,x.date),2,1))) = 29,366,365)
    --</MappingInfoStatus>
    )

    ,[Quarter_Name]=convert(Char(2),
    --<MappingInfoStatus Status="C" Column="Quarter_Name">
    'Q' + convert(varchar,convert(tinyint,datepart(quarter,x.date)))
    --</MappingInfoStatus>
    )

    ,[Year_Quarter_Name]=convert(Char(7),
    --<MappingInfoStatus Status="C" Column="Year_Quarter_Name">
    convert(varchar,year(x.date)) + '-Q' + convert(varchar,datepart(quarter,x.date))
    --</MappingInfoStatus>
    )

    ,[Quarter_Number_In_Year]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Quarter_Number_In_Year">
    datepart(quarter,x.date)
    --</MappingInfoStatus>
    )

    ,[Quarter_Number_Sequence]=convert(Int,
    --<MappingInfoStatus Status="C" Column="Quarter_Number_Sequence">
    convert(varchar,year(x.date)) + convert(varchar,datepart(quarter,x.date))
    --</MappingInfoStatus>
    )

    ,[Quarter_Begin_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Quarter_Begin_Date">
    DATEADD(qq, DATEDIFF(qq, 0, x.date), 0)
    --</MappingInfoStatus>
    )

    ,[Quarter_End_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Quarter_End_Date">
    case when x.date in ('1753-01-01','9999-12-31') then null else DATEADD (dd, -1, DATEADD(qq, DATEDIFF(qq, 0, x.date) +1, 0)) end
    --</MappingInfoStatus>
    )

    ,[Days_In_Quarter]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Days_In_Quarter">
    case when x.date in ('1753-01-01','9999-12-31') then null 
	else 
	DateDiff(dd,
	convert(date,DATEADD(qq, DATEDIFF(qq, 0, x.date), 0)),
	convert(date,DATEADD (dd, -1, DATEADD(qq, DATEDIFF(qq, 0, x.date) +1, 0))) )
	end
    --</MappingInfoStatus>
    )

    ,[Month_Name]=convert(VarChar(9),
    --<MappingInfoStatus Status="C" Column="Month_Name">
    datename(month,x.date)
    --</MappingInfoStatus>
    )

    ,[Month_Year_Name]=convert(VarChar(14),
    --<MappingInfoStatus Status="C" Column="Month_Year_Name">
    datename(month,x.date) + ' ' + convert(varchar,year(x.date))
    --</MappingInfoStatus>
    )

    ,[Year_Month_Yyyy_Mm]=convert(Char(7),
    --<MappingInfoStatus Status="C" Column="Year_Month_Yyyy_Mm">
    convert(varchar,year(x.date)) + '-' + convert(varchar(2),right('00' + convert(varchar,month(x.date)),2))
    --</MappingInfoStatus>
    )

    ,[Month_Abbr]=convert(Char(3),
    --<MappingInfoStatus Status="C" Column="Month_Abbr">
    datename(month,x.date)
    --</MappingInfoStatus>
    )

    ,[Month_Year_Abbr]=convert(Char(8),
    --<MappingInfoStatus Status="C" Column="Month_Year_Abbr">
    left(datename(month,x.date),3) + ' ' + convert(VARCHAR(4),year(x.date))
    --</MappingInfoStatus>
    )

    ,[Month_Number_In_Year]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Month_Number_In_Year">
    datepart(m,x.date)
    --</MappingInfoStatus>
    )

    ,[Month_Number_In_Quarter]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Month_Number_In_Quarter">
    case when datepart(m,x.date) in (1,4,7,10) then 1
		 when datepart(m,x.date) in  (2,5,8,11) then 2 else 3 end
    --</MappingInfoStatus>
    )

    ,[Month_Number_Sequence]=convert(Int,
    --<MappingInfoStatus Status="C" Column="Month_Number_Sequence">
    convert(varchar,year(x.date)) + convert(varchar,month(x.date))
    --</MappingInfoStatus>
    )

    ,[Month_Begin_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Month_Begin_Date">
    dateadd(dd,1,eomonth(x.date,-1))
    --</MappingInfoStatus>
    )

    ,[Month_End_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Month_End_Date">
    eomonth(x.date)
    --</MappingInfoStatus>
    )

    ,[Days_In_Month]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Days_In_Month">
    day(eomonth(x.date))
    --</MappingInfoStatus>
    )

    ,[Week_Name]=convert(Char(7),
    --<MappingInfoStatus Status="C" Column="Week_Name">
    'Week ' + convert(varchar, datepart(ww,x.date))
    --</MappingInfoStatus>
    )

    ,[Week_Abbr]=convert(Char(4),
    --<MappingInfoStatus Status="C" Column="Week_Abbr">
    'WK ' + convert(varchar,Datepart(ww,x.date))
    --</MappingInfoStatus>
    )

    ,[Year_Week_Name]=convert(Char(12),
    --<MappingInfoStatus Status="C" Column="Year_Week_Name">
    convert(varchar,year(x.date)) + ' Wk ' + convert(varchar,datepart(ww,x.date))
    --</MappingInfoStatus>
    )

    ,[Year_Week_Abbr]=convert(Char(9),
    --<MappingInfoStatus Status="C" Column="Year_Week_Abbr">
    convert(varchar,year(x.date)) + '-' + right('00' + convert(varchar,datepart(week,x.date)),2)
    --</MappingInfoStatus>
    )

    ,[Week_Desc_Short]=convert(Char(19),
    --<MappingInfoStatus Status="C" Column="Week_Desc_Short">
    'WK ' + convert(varchar, Datepart(ww,x.date))
    --</MappingInfoStatus>
    )

    ,[Week_Desc]=convert(Char(32),
    --<MappingInfoStatus Status="C" Column="Week_Desc">
    'Week ' + convert(varchar,datepart(ww,x.date))
    --</MappingInfoStatus>
    )

    ,[Week_Begin_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Week_Begin_Date">
    case when x.date in ('1753-01-01','9999-12-31') then null 
	else 
    DATEADD(wk,DATEDIFF(wk,0,x.date),-1)
	end
    --</MappingInfoStatus>
    )

    ,[Week_End_Date]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Week_End_Date">
    case when x.date in ('1753-01-01','9999-12-31') then null 
	else 
    DATEADD(wk,DATEDIFF(wk,0,x.date),5)
	end
    --</MappingInfoStatus>
    )

    ,[Week_Number_In_Year]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Week_Number_In_Year">
    datepart(ww,x.date)
    --</MappingInfoStatus>
    )

    ,[Week_Number_Sequence]=convert(Int,
    --<MappingInfoStatus Status="C" Column="Week_Number_Sequence">
    datepart(ww,x.date)
    --</MappingInfoStatus>
    )

    ,[Date_Of_Day]=convert(Date,
    --<MappingInfoStatus Status="C" Column="Date_Of_Day">
    x.date
    --</MappingInfoStatus>
    )

    ,[Date_String]=convert(Char(10),
    --<MappingInfoStatus Status="C" Column="Date_String">
    convert(date,x.date,120)
    --</MappingInfoStatus>
    )

    ,[Date_Desc]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="Date_Desc">
    x.date
    --</MappingInfoStatus>
    )

    ,[Date_Desc_Short]=convert(Char(16),
    --<MappingInfoStatus Status="C" Column="Date_Desc_Short">
    convert(date,x.date,102)
    --</MappingInfoStatus>
    )

    ,[Day_Number_In_Year]=convert(SmallInt,
    --<MappingInfoStatus Status="C" Column="Day_Number_In_Year">
    datepart(dy,x.date)
    --</MappingInfoStatus>
    )

    ,[First_Day_In_Year_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="First_Day_In_Year_Ind">
    case when datepart(d,x.date) = '01' and datepart(m,x.date) = '01' then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Last_Day_In_Year_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="Last_Day_In_Year_Ind">
    case when datepart(d,x.date) = '31' and datepart(m,x.date) = '12' then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Day_Number_In_Quarter]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Day_Number_In_Quarter">
    DateDiff(dd,CONVERT(DATE,dateadd(qq, datediff(qq,0, x.date),0)),x.date)+1
    --</MappingInfoStatus>
    )

    ,[First_Day_In_Quarter_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="First_Day_In_Quarter_Ind">
    case when convert(tinyint,DateDiff(dd,CONVERT(DATE,dateadd(qq, datediff(qq,0, x.date),0)),x.date)+1) = 1 then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Last_Day_In_Quarter_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="Last_Day_In_Quarter_Ind">
    case when DATEADD(qq,DATEDIFF(qq,-1,x.date),-1) = x.date then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Day_Number_In_Month]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Day_Number_In_Month">
    day(x.date)
    --</MappingInfoStatus>
    )

    ,[First_Day_In_Month_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="First_Day_In_Month_Ind">
    case when day(x.date) = 1 then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Last_Day_In_Month_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="Last_Day_In_Month_Ind">
    case when eomonth(x.date) = x.date then 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Weekday_Name]=convert(Char(9),
    --<MappingInfoStatus Status="C" Column="Weekday_Name">
    DateName(WEEKDAY,x.date)
    --</MappingInfoStatus>
    )

    ,[Weekday_Abbr]=convert(Char(3),
    --<MappingInfoStatus Status="C" Column="Weekday_Abbr">
    left(DateName(WEEKDAY,x.date),3)
    --</MappingInfoStatus>
    )

    ,[Day_Number_In_Week]=convert(TinyInt,
    --<MappingInfoStatus Status="C" Column="Day_Number_In_Week">
    DATEPART(DW,X.DATE)
    --</MappingInfoStatus>
    )

    ,[First_Day_In_Week_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="First_Day_In_Week_Ind">
    CASE WHEN DATEPART(day,X.DATE) = 1 THEN 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Last_Day_In_Week_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="Last_Day_In_Week_Ind">
    CASE WHEN DATEPART(day,X.DATE) = 7 THEN 'Y' else 'N' end
    --</MappingInfoStatus>
    )

    ,[Day_Number_Sequence]=convert(Int,
    --<MappingInfoStatus Status="C" Column="Day_Number_Sequence">
    datepart(yyyy,x.date)*1000 + datepart(dy,x.date)
    --</MappingInfoStatus>
    )

    ,[Weekday_Ind]=convert(Char(1),
    --<MappingInfoStatus Status="C" Column="Weekday_Ind">
    case when datepart(dw,x.date) in (1,7) then 'N' else 'Y' end
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    'Static'
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    'OES-Zip'
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    Getdate()
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom>
  from @datetable X
  order by X.date
  --</MappingInfoFrom>
--</MappingInfo>