/****** Object:  StoredProcedure [dbo].[sp_iMart_Transform_dim_District_edfi]    Script Date: 4:40:40 PM ******/
CREATE procedure [dbo].[sp_iMart_Transform_dim_District_edfi]
(
     @SAID varchar(30) = null,
     @Batch_Period_List varchar(max) = null
)
as

-- ============================================================================
-- Script UTC date: 2019-04-15 18:11:01
-- Description: Generated by OtisEd iMart Wizard Tool
-- Copyright: ©2019 Otis Educational Systems, Inc. All Rights Reserved
-- ============================================================================

-- Example:  exec [dbo].[sp_iMart_Transform_dim_District_edfi] @SAID='all', @Batch_Period_List='all'
/* 
<StatusList>
  <Status Code = "A">Assigned Waiting for mapping</Status>
  <Status Code = "I">Ignore for this implementation</Status>
  <Status Code = "M">Mapped and waiting for Review</Status>
  <Status Code = "U">Reviewed and deemed unacceptable.Needs Remapping</Status>
  <Status Code = "H">On Hold for this iteration, non-blocking</Status>
  <Status Code = "C"> Completed</Status>
</StatusList>
*/

--parameter processing
declare @BPLxml xml = (select cast('<a>'+replace(@Batch_Period_List,',','</a><a>') + '</a>' as xml))
declare @BPLtable table(Batch_Period varchar(50), primary key (Batch_Period))
insert into @BPLtable(Batch_Period) 
select ltrim(rtrim(t.value('.','nvarchar(50)'))) as Batch_Period from @BPLxml.nodes('/a') as x(t) where len(@Batch_Period_List)>0

declare @SAIDxml xml = (select cast('<a>'+replace(@SAID,',','</a><a>') + '</a>' as xml))
declare @SAIDtable table(SAID nvarchar(30), Agency nvarchar(30), primary key (SAID))
insert into @SAIDtable(SAID) 
select ltrim(rtrim(t.value('.','nvarchar(30)'))) as SAID from @SAIDxml.nodes('/a') as x(t) where len(@SAID)>0
update @SAIDtable set Agency=case when patindex('%-%', said) > 1 then left(said, patindex('%-%', said)-1 ) else said end

--<MappingInfo Table="dim_District"> 

--<MappingInfoCommon>
declare @ActiveSchoolYear int = (select top 1 SchoolYear from edfi.SchoolYearType where CurrentSchoolYear=1)
--</MappingInfoCommon>

select
     [District_Id]=convert(VarChar(16),
    --<MappingInfoStatus Status="C" Column="District_Id">
    [edfi].[EducationOrganization].EducationOrganizationId
    --</MappingInfoStatus>
    )

    ,[District_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="District_Name">
    [edfi].[EducationOrganization].NameOfInstitution
    --</MappingInfoStatus>
    )

    ,[Superintendent_Name]=convert(VarChar(36),
    --<MappingInfoStatus Status="C" Column="Superintendent_Name">
	IsNull((
	select top (1) s.LastSurname + ', '+s.FirstName
	  from [edfi].[StaffEducationOrganizationAssignmentAssociation] a
	  join [edfi].[Staff] s on s.StaffUSI=a.StaffUSI
	  join edfi.descriptor d 
		on d.descriptorid=a.StaffClassificationDescriptorId and d.CodeValue='Superintendent'
	  where a.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
    --</MappingInfoStatus>
    )

    ,[State_Abbr]=convert(Char(2),
    --<MappingInfoStatus Status="C" Column="State_Abbr">
	IsNull((
	select top (1) eo.ShortNameOfInstitution
	  from [edfi].[EducationOrganization] eo 
	 where eo.EducationOrganizationId=[edfi].[LocalEducationAgency].StateEducationAgencyId
	 ),'')
    --</MappingInfoStatus>
    )

    ,[State_Name]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="State_Name">
	IsNull((
	select top (1) eo.NameOfInstitution
	  from [edfi].[EducationOrganization] eo 
	 where eo.EducationOrganizationId=[edfi].[LocalEducationAgency].StateEducationAgencyId
	 ),'')
    --</MappingInfoStatus>
    )

    ,[County_Name]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="County_Name">
    IsNull((
	select top (1) addr.NameOfCounty
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
    --</MappingInfoStatus>
    )

    ,[REA_Name]=convert(VarChar(60),
    --<MappingInfoStatus Status="C" Column="REA_Name">
	IsNull((
	select top (1) eo.NameOfInstitution
	  from [edfi].[EducationOrganization] eo 
	 where eo.EducationOrganizationId=[edfi].[LocalEducationAgency].EducationServiceCenterId
	 ),[edfi].[LocalEducationAgency].EducationServiceCenterId)
    --</MappingInfoStatus>
    )

    ,[REA_Abbr]=convert(VarChar(36),
    --<MappingInfoStatus Status="C" Column="REA_Abbr">
	IsNull((
	select top (1) eo.ShortNameOfInstitution
	  from [edfi].[EducationOrganization] eo 
	 where eo.EducationOrganizationId=[edfi].[LocalEducationAgency].EducationServiceCenterId
	 ),[edfi].[LocalEducationAgency].EducationServiceCenterId)
    --</MappingInfoStatus>
    )

    ,[District_Academic_Year_Began]=convert(VarChar(9),
    --<MappingInfoStatus Status="I" Column="District_Academic_Year_Began">
    0 -- No source in EdFi
    --</MappingInfoStatus>
    )

    ,[District_Academic_Year_Ended]=convert(VarChar(9),
    --<MappingInfoStatus Status="I" Column="District_Academic_Year_Ended">
    0 -- No source in EdFi
    --</MappingInfoStatus>
    )

    ,[District_Phone]=convert(VarChar(24),
    --<MappingInfoStatus Status="C" Column="District_Phone">
	IsNull((
	select top (1) t.TelephoneNumber
	  from [edfi].[EducationOrganizationInstitutionTelephone] t
	  join [edfi].[Descriptor] d on d.DescriptorId=t.InstitutionTelephoneNumberTypeDescriptorId and d.CodeValue='Main'
	 where t.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
	--</MappingInfoStatus>
    )

    ,[District_Address_1]=convert(VarChar(36),
    --<MappingInfoStatus Status="C" Column="District_Address_1">
    IsNull((
	select top (1) addr.StreetNumberName
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
    --</MappingInfoStatus>
    )

    ,[District_Address_2]=convert(VarChar(36),
    --<MappingInfoStatus Status="C" Column="District_Address_2">
    IsNull((
	select top (1) addr.ApartmentRoomSuiteNumber
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
    --</MappingInfoStatus>
    )

    ,[District_City]=convert(VarChar(24),
    --<MappingInfoStatus Status="C" Column="District_City">
    IsNull((
	select top (1) addr.City
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
    --</MappingInfoStatus>
    )

    ,[District_State]=convert(VarChar(2),
    --<MappingInfoStatus Status="C" Column="District_State">
    IsNull((
	select top (1) st_d.CodeValue
	  from [edfi].[EducationOrganizationAddress] addr
	  join [edfi].[Descriptor] st_d on st_d.DescriptorId=addr.StateAbbreviationDescriptorId
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
    --</MappingInfoStatus>
    )

    ,[District_Postal_Cd]=convert(VarChar(10),
    --<MappingInfoStatus Status="C" Column="District_Postal_Cd">
    IsNull((
	select top (1) addr.PostalCode
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),'')
    --</MappingInfoStatus>
    )

    ,[District_Latitude]=convert(Decimal(9,6),
    --<MappingInfoStatus Status="C" Column="District_Latitude">
    IsNull((
	select top (1) addr.Latitude
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),0.0)
    --</MappingInfoStatus>
    )

    ,[District_Longitude]=convert(Decimal(9,6),
    --<MappingInfoStatus Status="C" Column="District_Longitude">
    IsNull((
	select top (1) addr.Longitude
	  from [edfi].[EducationOrganizationAddress] addr
	 where addr.EducationOrganizationId=[edfi].[EducationOrganization].EducationOrganizationId
	),0.0)
    --</MappingInfoStatus>
    )

    ,[Batch_Period]=convert(VarChar(50),
    --<MappingInfoStatus Status="C" Column="Batch_Period">
    @ActiveSchoolYear
    --</MappingInfoStatus>
    )

    ,[SAID]=convert(VarChar(30),
    --<MappingInfoStatus Status="C" Column="SAID">
    [edfi].[LocalEducationAgency].SAID
    --</MappingInfoStatus>
    )

    ,[Date_Stamp]=convert(DateTime2,
    --<MappingInfoStatus Status="C" Column="Date_Stamp">
    [edfi].[EducationOrganization].LastModifiedDate
    --</MappingInfoStatus>
    )

  --<MappingInfoFrom> -- select count(*) -- Select top (10) *
  FROM [edfi].[LocalEducationAgency]
  join [edfi].[EducationOrganization] 
    on [edfi].[EducationOrganization].EducationOrganizationId=[edfi].[LocalEducationAgency].LocalEducationAgencyId
  --join [edfi].[EducationOrganizationCategory] eoc
  --  on eo.EducationOrganizationId=eoc.EducationOrganizationId
  --join edfi.Descriptor os on os.DescriptorId=eo.OperationalStatusDescriptorId
  --join edfi.Descriptor leatype on leatype.DescriptorId=lea.LocalEducationAgencyCategoryDescriptorId
 where (@Batch_Period_List='all' or @ActiveSchoolYear in (select Batch_Period from @BPLtable))
   and (IsNull(@SAID,'all') in ('all','any') or [edfi].[LocalEducationAgency].SAID in (select SAID from @SAIDtable) )
  --</MappingInfoFrom>
--</MappingInfo>